# config.py

from roles import WEREWOLF, VILLAGER, SEER, WITCH, HUNTER

DEFAULT_ROLE_SETUP = [
    WEREWOLF,
    WEREWOLF,
    VILLAGER,
    VILLAGER,
    SEER,
    WITCH,
    HUNTER,
]

TEN_PLAYER_ROLE_SETUP = [
    WEREWOLF,
    WEREWOLF,
    WEREWOLF,
    SEER,
    WITCH,
    HUNTER,
    VILLAGER,
    VILLAGER,
    VILLAGER,
    VILLAGER,
]

DEFAULT_MAX_ROUNDS = 20
DEFAULT_NUM_GAMES = 500
DEFAULT_RANDOM_SEED = 42
TEN_PLAYER_INITIAL_P_WOLF = 0.30
TEN_PLAYER_SPEECH_SIGNAL_SCALE = 0.70
TEN_PLAYER_HERDING_WEIGHT_SCALE = 0.60
TEN_PLAYER_CREDIBILITY_COST_SCALE = 0.75
DEFAULT_WITCH_POISON_THRESHOLD = 0.15
DEFAULT_ENABLE_HUNTER = True
DEFAULT_ENABLE_HERDING = True
DEFAULT_HERDING_ALPHA = 0.5
DEFAULT_HERDING_BETA = 0.3
DEFAULT_HERDING_GAMMA = 0.2
DEFAULT_ENABLE_ROLE_PRIOR = True
DEFAULT_ROLE_PRIOR_ALPHA = 0.45
DEFAULT_ROLE_PRIOR_BETA = 0.25
DEFAULT_ROLE_PRIOR_GAMMA = 0.20
DEFAULT_ROLE_PRIOR_DELTA = 0.10
DEFAULT_ENABLE_WOLF_STRATEGY = True
DEFAULT_WOLF_KILL_STRATEGY = "threat_based"
DEFAULT_WOLF_KILL_NOISE_LEVEL = 0.05
DEFAULT_ENABLE_WOLF_DECEPTION = True
DEFAULT_WOLF_DECEPTION_STRATEGY = "mixed"
DEFAULT_ENABLE_DECEPTION_CREDIBILITY = True
DEFAULT_ENABLE_SPEAKER_MEMORY = True
DEFAULT_ENABLE_LAST_WORDS = False
DEFAULT_ENABLE_RISK_PREFERENCE = False
DEFAULT_SPEAKER_MEMORY_WEIGHT = 0.15
DEFAULT_TRUST_VOTE_WEIGHT = DEFAULT_SPEAKER_MEMORY_WEIGHT
DEFAULT_ENABLE_TRUST_WEIGHTED_SPEECH = True
DEFAULT_TRUST_SPEECH_MIN_MULTIPLIER = 0.5
DEFAULT_TRUST_SPEECH_MAX_MULTIPLIER = 1.5
DEFAULT_ENABLE_TRUST_WEIGHTED_HERDING = True
DEFAULT_TRUST_HERDING_MIN_MULTIPLIER = 0.4
DEFAULT_TRUST_HERDING_MAX_MULTIPLIER = 1.4
