"""Curated DOI and recency audit data for R7.1.

R7.1 does not delete or rewrite the original R7 source set. It creates a
stricter final-bibliography layer in which every final source has a DOI and
recent sources are preferred unless a source is a justified foundation.
"""

from __future__ import annotations

from literature_stage_r7_data import PROJECT_FINDINGS, SOURCES


VERIFICATION_DATE = "2026-08-05"
RECENT_START_YEAR = 2016
RECENT_END_YEAR = 2026


REPLACEMENT_SOURCES = [
    {
        "source_id": "S065",
        "citation_key": "geirhos2020shortcut",
        "title": "Shortcut learning in deep neural networks",
        "authors": "Robert Geirhos; Joern-Henrik Jacobsen; Claudio Michaelis; Richard Zemel; Wieland Brendel; Matthias Bethge; Felix A. Wichmann",
        "year": "2020",
        "venue": "Nature Machine Intelligence",
        "doi": "10.1038/s42256-020-00257-z",
        "url": "https://doi.org/10.1038/s42256-020-00257-z",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "bow_domain_shift",
        "secondary_domains": "offline_policy;simulation_validation",
        "relevance": "Recent DOI-bearing support for shortcut learning and template dependence.",
        "exact_claim_supported": "Models can rely on shortcut signals that fail under distribution shift.",
        "limitations": "Deep learning review/perspective, not Werewolf-specific.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Nature Machine Intelligence DOI record",
    },
    {
        "source_id": "S066",
        "citation_key": "abar2017abms",
        "title": "Agent Based Modelling and Simulation tools: A review of the state-of-art software",
        "authors": "Sameera Abar; Georgios K. Theodoropoulos; Pierre Lemarinier; Gregory M. P. O'Hare",
        "year": "2017",
        "venue": "Computer Science Review",
        "doi": "10.1016/j.cosrev.2017.03.001",
        "url": "https://doi.org/10.1016/j.cosrev.2017.03.001",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "simulation_validation",
        "secondary_domains": "social_deduction",
        "relevance": "Recent survey of agent-based modelling and simulation tools.",
        "exact_claim_supported": "Agent-based modelling tools and validation choices require explicit documentation.",
        "limitations": "General ABMS survey, not hidden-role games.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Elsevier DOI record",
    },
    {
        "source_id": "S067",
        "citation_key": "grimm2020odd",
        "title": "The ODD Protocol for Describing Agent-Based and Other Simulation Models: A Second Update to Improve Clarity, Replication, and Structural Realism",
        "authors": "Volker Grimm; Steven F. Railsback; Christian E. Vincenot; Uta Berger; Cara A. Gallagher; Donald L. DeAngelis; Bruce Edmonds; Jiaqi Ge; Jarl Giske; Jurgen Groeneveld; Alice S. A. Johnston; Alexander Milles; Jacob Nabe-Nielsen; J. Gareth Polhill; Viktoriia Radchuk; Marie-Sophie Rohwaeder; Richard A. Stillman; Jan Thiele; Daniel Ayllon",
        "year": "2020",
        "venue": "Journal of Artificial Societies and Social Simulation",
        "doi": "10.18564/jasss.4259",
        "url": "https://doi.org/10.18564/jasss.4259",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "simulation_validation",
        "secondary_domains": "source_traceability",
        "relevance": "Recent DOI-bearing ODD protocol update.",
        "exact_claim_supported": "Simulation studies need transparent model description, replication, and validation documentation.",
        "limitations": "ABM documentation protocol, not a Werewolf model.",
        "quality_grade": "A",
        "metadata_status": "verified_government_and_journal_record",
        "verification_source": "USGS/JASSS DOI record",
    },
    {
        "source_id": "S068",
        "citation_key": "minaee2021textclassification",
        "title": "Deep Learning--based Text Classification: A Comprehensive Review",
        "authors": "Shervin Minaee; Nal Kalchbrenner; Erik Cambria; Narjes Nikzad; Meysam Chenaghlu; Jianfeng Gao",
        "year": "2021",
        "venue": "ACM Computing Surveys",
        "doi": "10.1145/3439726",
        "url": "https://doi.org/10.1145/3439726",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "bow_domain_shift",
        "secondary_domains": "offline_policy",
        "relevance": "Recent DOI-bearing text-classification review.",
        "exact_claim_supported": "Text classification performance depends on representation choices, datasets, and model validation.",
        "limitations": "General NLP review rather than social deduction dialogue.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "ACM DOI record",
    },
    {
        "source_id": "S069",
        "citation_key": "prudencio2024offline",
        "title": "A Survey on Offline Reinforcement Learning: Taxonomy, Review, and Open Problems",
        "authors": "Rafael Figueiredo Prudencio; Marcos Ricardo Omena Albuquerque Maximo; Esther Luna Colombini",
        "year": "2024",
        "venue": "IEEE Transactions on Neural Networks and Learning Systems",
        "doi": "10.1109/TNNLS.2023.3250269",
        "url": "https://doi.org/10.1109/TNNLS.2023.3250269",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "offline_policy",
        "secondary_domains": "risk_metrics;simulation_validation",
        "relevance": "Recent DOI-bearing offline RL survey.",
        "exact_claim_supported": "Offline RL policies need careful evaluation because deployment without online interaction is risky.",
        "limitations": "Review source and not specific to Werewolf.",
        "quality_grade": "A",
        "metadata_status": "verified_pubmed_and_dblp_record",
        "verification_source": "PubMed/IEEE DOI record",
    },
    {
        "source_id": "S070",
        "citation_key": "gottesman2019healthcare",
        "title": "Guidelines for reinforcement learning in healthcare",
        "authors": "Omer Gottesman; Fredrik Johansson; Matthieu Komorowski; A. Aldo Faisal; David Sontag; Finale Doshi-Velez; Leo Anthony Celi",
        "year": "2019",
        "venue": "Nature Medicine",
        "doi": "10.1038/s41591-018-0310-5",
        "url": "https://doi.org/10.1038/s41591-018-0310-5",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "offline_policy",
        "secondary_domains": "simulation_validation;risk_metrics",
        "relevance": "Recent DOI-bearing safety guidance for RL from observational data.",
        "exact_claim_supported": "Policies learned from observational data require risk-conscious validation before deployment.",
        "limitations": "Healthcare decision context, not social deduction.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Nature Medicine DOI record",
    },
    {
        "source_id": "S071",
        "citation_key": "kamenica2019persuasion",
        "title": "Bayesian Persuasion and Information Design",
        "authors": "Emir Kamenica",
        "year": "2019",
        "venue": "Annual Review of Economics",
        "doi": "10.1146/annurev-economics-080218-025739",
        "url": "https://doi.org/10.1146/annurev-economics-080218-025739",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "asymmetric_information",
        "secondary_domains": "deception_misinformation;behavioral_finance",
        "relevance": "Recent review of information disclosure and persuasion.",
        "exact_claim_supported": "Information disclosure can strategically shape receiver decisions.",
        "limitations": "Economic review, not a game simulation.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Annual Reviews DOI record",
    },
    {
        "source_id": "S072",
        "citation_key": "bergemann2018price",
        "title": "The Design and Price of Information",
        "authors": "Dirk Bergemann; Alessandro Bonatti; Alex Smolin",
        "year": "2018",
        "venue": "American Economic Review",
        "doi": "10.1257/aer.20161079",
        "url": "https://doi.org/10.1257/aer.20161079",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "asymmetric_information",
        "secondary_domains": "behavioral_finance",
        "relevance": "Recent DOI-bearing information-design paper.",
        "exact_claim_supported": "Supplemental information has value depending on prior information quality.",
        "limitations": "Market information design, not Seer mechanics.",
        "quality_grade": "A",
        "metadata_status": "verified_aea_record",
        "verification_source": "AEA DOI record",
    },
    {
        "source_id": "S073",
        "citation_key": "cookson2023echo",
        "title": "Echo Chambers",
        "authors": "J. Anthony Cookson; Joseph E. Engelberg; William Mullins",
        "year": "2023",
        "venue": "Review of Financial Studies",
        "doi": "10.1093/rfs/hhac058",
        "url": "https://doi.org/10.1093/rfs/hhac058",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "herding_trust;deception_misinformation",
        "relevance": "Recent investor social-network evidence on selective exposure.",
        "exact_claim_supported": "Financial social networks can create echo chambers that shape beliefs and outcomes.",
        "limitations": "Investor-network evidence, not Werewolf agents.",
        "quality_grade": "A",
        "metadata_status": "verified_university_and_index_record",
        "verification_source": "OUP DOI record via university/index metadata",
    },
    {
        "source_id": "S074",
        "citation_key": "fissler2016elicitability",
        "title": "Higher Order Elicitability and Osband's Principle",
        "authors": "Tobias Fissler; Johanna F. Ziegel",
        "year": "2016",
        "venue": "Annals of Statistics",
        "doi": "10.1214/16-AOS1439",
        "url": "https://doi.org/10.1214/16-AOS1439",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "risk_metrics",
        "secondary_domains": "behavioral_finance",
        "relevance": "Recent DOI-bearing risk-measure elicitability source.",
        "exact_claim_supported": "VaR and expected shortfall can be jointly evaluated under suitable scoring frameworks.",
        "limitations": "Statistical risk-measure theory, not game payoff design.",
        "quality_grade": "A",
        "metadata_status": "verified_institutional_record",
        "verification_source": "Annals of Statistics DOI record",
    },
    {
        "source_id": "S075",
        "citation_key": "jiao2020socialmedia",
        "title": "Social media, news media and the stock market",
        "authors": "Peiran Jiao; Andre Veiga; Ansgar Walther",
        "year": "2020",
        "venue": "Journal of Economic Behavior & Organization",
        "doi": "10.1016/j.jebo.2020.03.002",
        "url": "https://doi.org/10.1016/j.jebo.2020.03.002",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "herding_trust;deception_misinformation",
        "relevance": "Recent DOI-bearing market narrative and social-media evidence.",
        "exact_claim_supported": "Social media coverage can affect volatility and trading volume differently from news media.",
        "limitations": "Market panel data, not hidden-role voting.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Elsevier DOI record",
    },
    {
        "source_id": "S076",
        "citation_key": "cresci2018fake",
        "title": "$FAKE: Evidence of Spam and Bot Activity in Stock Microblogs on Twitter",
        "authors": "Stefano Cresci; Fabrizio Lillo; Daniele Regoli; Serena Tardelli; Maurizio Tesconi",
        "year": "2018",
        "venue": "International AAAI Conference on Web and Social Media",
        "doi": "10.1609/icwsm.v12i1.15073",
        "url": "https://doi.org/10.1609/icwsm.v12i1.15073",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "deception_misinformation",
        "relevance": "Recent DOI-bearing evidence of spam/bot activity in stock microblogs.",
        "exact_claim_supported": "Market-related social media can contain coordinated manipulation-like behavior.",
        "limitations": "Detection study, not causal game-policy analysis.",
        "quality_grade": "A",
        "metadata_status": "verified_aaai_record",
        "verification_source": "AAAI DOI record",
    },
    {
        "source_id": "S077",
        "citation_key": "loughran2020textual",
        "title": "Textual Analysis in Finance",
        "authors": "Tim Loughran; Bill McDonald",
        "year": "2020",
        "venue": "Annual Review of Financial Economics",
        "doi": "10.1146/annurev-financial-012820-032249",
        "url": "https://doi.org/10.1146/annurev-financial-012820-032249",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "bow_domain_shift;deception_misinformation",
        "relevance": "Recent DOI-bearing review of text and lexicon analysis in finance.",
        "exact_claim_supported": "Lexicon-based finance text analysis is useful but construct validity must be explicit.",
        "limitations": "Finance text, not Werewolf speech.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Annual Reviews DOI record",
    },
    {
        "source_id": "S078",
        "citation_key": "zhou2020fakenews",
        "title": "A Survey of Fake News: Fundamental Theories, Detection Methods, and Opportunities",
        "authors": "Xinyi Zhou; Reza Zafarani",
        "year": "2020",
        "venue": "ACM Computing Surveys",
        "doi": "10.1145/3395046",
        "url": "https://doi.org/10.1145/3395046",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "deception_misinformation",
        "secondary_domains": "bow_domain_shift;herding_trust",
        "relevance": "Recent DOI-bearing fake-news detection survey.",
        "exact_claim_supported": "Fake-news detection can use writing style, propagation, and source credibility features.",
        "limitations": "Survey source rather than causal experiment.",
        "quality_grade": "A",
        "metadata_status": "verified_acm_record",
        "verification_source": "ACM DOI record",
    },
    {
        "source_id": "S079",
        "citation_key": "toyokawa2019social",
        "title": "Social learning strategies regulate the wisdom and madness of interactive crowds",
        "authors": "Wataru Toyokawa; Andrew Whalen; Kevin N. Laland",
        "year": "2019",
        "venue": "Nature Human Behaviour",
        "doi": "10.1038/s41562-018-0518-x",
        "url": "https://doi.org/10.1038/s41562-018-0518-x",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "herding_trust",
        "secondary_domains": "simulation_validation",
        "relevance": "Recent DOI-bearing social-learning evidence.",
        "exact_claim_supported": "Social learning strategies can produce both crowd wisdom and crowd failure.",
        "limitations": "Human online experiment, not a Werewolf simulation.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Nature Human Behaviour DOI record",
    },
    {
        "source_id": "S080",
        "citation_key": "jia2020rumors",
        "title": "Can social media distort price discovery? Evidence from merger rumors",
        "authors": "Wei Jia; Giorgia Redigolo; Susan Shu; Jenny Zhao",
        "year": "2020",
        "venue": "Journal of Accounting and Economics",
        "doi": "10.1016/j.jacceco.2020.101334",
        "url": "https://doi.org/10.1016/j.jacceco.2020.101334",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "deception_misinformation;herding_trust",
        "relevance": "Recent DOI-bearing rumor and price-discovery evidence.",
        "exact_claim_supported": "Speculative social-media rumors can distort price discovery.",
        "limitations": "Financial event study, not simulated voting.",
        "quality_grade": "A",
        "metadata_status": "verified_institutional_record",
        "verification_source": "Elsevier/institutional DOI record",
    },
    {
        "source_id": "S081",
        "citation_key": "bergemann2019unified",
        "title": "Information Design: A Unified Perspective",
        "authors": "Dirk Bergemann; Stephen Morris",
        "year": "2019",
        "venue": "Journal of Economic Literature",
        "doi": "10.1257/jel.20181489",
        "url": "https://doi.org/10.1257/jel.20181489",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "asymmetric_information",
        "secondary_domains": "behavioral_finance;simulation_validation",
        "relevance": "Recent DOI-bearing review of information design.",
        "exact_claim_supported": "Information structures can be compared by how they change behavior in games.",
        "limitations": "Economic theory review, not direct DURF experiment.",
        "quality_grade": "A",
        "metadata_status": "verified_aea_record",
        "verification_source": "AEA DOI record",
    },
    {
        "source_id": "S082",
        "citation_key": "bergemann2016bayes",
        "title": "Bayes Correlated Equilibrium and the Comparison of Information Structures in Games",
        "authors": "Dirk Bergemann; Stephen Morris",
        "year": "2016",
        "venue": "Theoretical Economics",
        "doi": "10.3982/TE1808",
        "url": "https://doi.org/10.3982/TE1808",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "asymmetric_information",
        "secondary_domains": "social_deduction;simulation_validation",
        "relevance": "Recent DOI-bearing game-theory source on information structures.",
        "exact_claim_supported": "Information structures can be formally compared in incomplete-information games.",
        "limitations": "Equilibrium theory, not simulation evidence.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Wiley/Theoretical Economics DOI record",
    },
    {
        "source_id": "S083",
        "citation_key": "christoffersen2019riskherding",
        "title": "Individual risk tolerance and herding behaviors in financial forecasts",
        "authors": "Jeppe Christoffersen; Sara Staehr",
        "year": "2019",
        "venue": "European Financial Management",
        "doi": "10.1111/eufm.12231",
        "url": "https://doi.org/10.1111/eufm.12231",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "herding_trust",
        "secondary_domains": "behavioral_finance;risk_metrics",
        "relevance": "Recent DOI-bearing evidence tying risk tolerance to herding forecasts.",
        "exact_claim_supported": "Risk preference can influence herding behavior in financial forecasts.",
        "limitations": "Forecasting experiment rather than role-playing simulation.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Wiley DOI record",
    },
    {
        "source_id": "S084",
        "citation_key": "siganos2025fakenews",
        "title": "Trump's fake news and stock market returns",
        "authors": "Antonios Siganos",
        "year": "2025",
        "venue": "European Journal of Finance",
        "doi": "10.1080/1351847X.2024.2395927",
        "url": "https://doi.org/10.1080/1351847X.2024.2395927",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "deception_misinformation",
        "relevance": "Recent DOI-bearing financial fake-news evidence.",
        "exact_claim_supported": "Fake news can temporarily influence stock-market returns when believed by participants.",
        "limitations": "Political news setting, not Werewolf deception.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Taylor & Francis DOI record",
    },
    {
        "source_id": "S085",
        "citation_key": "dong2021socialmassmedia",
        "title": "How are social and mass media different in relation to the stock market? A study on topic coverage and predictive value",
        "authors": "Hang Dong; Jie Ren; Balaji Padmanabhan; Jeffrey V. Nickerson",
        "year": "2021",
        "venue": "Information & Management",
        "doi": "10.1016/j.im.2021.103588",
        "url": "https://doi.org/10.1016/j.im.2021.103588",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "bow_domain_shift;herding_trust",
        "relevance": "Recent DOI-bearing evidence on stock-market media coverage and predictive value.",
        "exact_claim_supported": "Different media sources carry different predictive value for stock-market outcomes.",
        "limitations": "Stock-market media data, not social deduction dialogue.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Elsevier DOI record",
    },
    {
        "source_id": "S086",
        "citation_key": "jeon2021newsjumps",
        "title": "News as sources of jumps in stock returns: Evidence from 21 million news articles for 9,000 companies",
        "authors": "Yoontae Jeon; Thomas H. McCurdy; Xiaofei Zhao",
        "year": "2021",
        "venue": "Journal of Financial Economics",
        "doi": "10.1016/j.jfineco.2021.08.002",
        "url": "https://doi.org/10.1016/j.jfineco.2021.08.002",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "bow_domain_shift;risk_metrics",
        "relevance": "Recent DOI-bearing finance text and event-risk source.",
        "exact_claim_supported": "News flow and content can be connected to jump risk in stock returns.",
        "limitations": "Empirical finance text analysis, not game payoff shocks.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "Elsevier DOI record",
    },
    {
        "source_id": "S087",
        "citation_key": "kou2016tailrisk",
        "title": "On the Measurement of Economic Tail Risk",
        "authors": "Steven Kou; Xianhua Peng",
        "year": "2016",
        "venue": "Operations Research",
        "doi": "10.1287/opre.2016.1539",
        "url": "https://doi.org/10.1287/opre.2016.1539",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "risk_metrics",
        "secondary_domains": "behavioral_finance",
        "relevance": "Recent DOI-bearing tail-risk metric discussion.",
        "exact_claim_supported": "Tail-risk measurement choices affect risk-management interpretation.",
        "limitations": "Economic tail risk, not game utility tail risk.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "INFORMS DOI record",
    },
    {
        "source_id": "S088",
        "citation_key": "embrechts2018rvar",
        "title": "Quantile-Based Risk Sharing",
        "authors": "Paul Embrechts; Haiyan Liu; Ruodu Wang",
        "year": "2018",
        "venue": "Operations Research",
        "doi": "10.1287/opre.2017.1716",
        "url": "https://doi.org/10.1287/opre.2017.1716",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "risk_metrics",
        "secondary_domains": "behavioral_finance",
        "relevance": "Recent DOI-bearing risk-sharing and VaR/ES source.",
        "exact_claim_supported": "VaR and expected shortfall are central but distinct risk measures.",
        "limitations": "Portfolio risk-sharing theory, not Werewolf payoff optimization.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
        "verification_source": "INFORMS DOI record",
    },
]


FINAL_ORIGINAL_SOURCE_IDS = {
    "S001",
    "S002",
    "S003",
    "S004",
    "S005",
    "S007",
    "S009",
    "S012",
    "S015",
    "S016",
    "S022",
    "S023",
    "S024",
    "S025",
    "S026",
    "S028",
    "S030",
    "S058",
    "S059",
    "S060",
}

FINAL_REPLACEMENT_SOURCE_IDS = {source["source_id"] for source in REPLACEMENT_SOURCES}
FINAL_SOURCE_IDS = FINAL_ORIGINAL_SOURCE_IDS | FINAL_REPLACEMENT_SOURCE_IDS


FOUNDATIONAL_EXCEPTIONS = {
    "S001": (
        "Formal Mafia partial-information model.",
        "No recent source replaces its role as the canonical formal Mafia model.",
        "S002;S005;S007",
        "Use narrowly for hidden-role game foundation.",
    ),
    "S009": (
        "Bayesian games under incomplete information.",
        "Later information-design sources extend but do not replace the original Bayesian-games foundation.",
        "S081;S082",
        "Use narrowly for incomplete-information foundation.",
    ),
    "S012": (
        "Canonical cheap-talk model.",
        "Recent persuasion and information-design sources build on it but do not replace the original strategic-communication formulation.",
        "S071;S081",
        "Use narrowly for cheap-talk foundation.",
    ),
    "S015": (
        "Canonical herd-behavior model.",
        "Recent social-learning and finance-herding papers extend but do not replace the original model.",
        "S079;S083",
        "Use narrowly for herding foundation.",
    ),
    "S016": (
        "Canonical informational-cascade model.",
        "Recent social-learning studies are companions rather than replacements for the original cascade theory.",
        "S079;S083",
        "Use narrowly for informational-cascade foundation.",
    ),
    "S030": (
        "Canonical stock-price manipulation model.",
        "Recent social-media manipulation sources are empirical companions, not replacements for the formal manipulation model.",
        "S076;S080;S084",
        "Use narrowly for market-manipulation foundation.",
    ),
    "S058": (
        "Original Sharpe-like risk-adjusted performance foundation.",
        "Recent risk-metric sources extend the family but do not replace the original Sharpe-ratio concept.",
        "S074;S087;S088",
        "Use narrowly for Sharpe-like metric foundation.",
    ),
    "S059": (
        "Original downside-risk performance measurement foundation.",
        "Recent tail-risk and VaR/ES sources are companions, not replacements for Sortino-like framing.",
        "S074;S087;S088",
        "Use narrowly for Sortino/downside-risk metric foundation.",
    ),
    "S060": (
        "Canonical CVaR optimization foundation.",
        "Recent risk-measure sources extend validation and tail-risk measurement.",
        "S074;S087;S088",
        "Use narrowly for CVaR-like metric foundation.",
    ),
}


NO_DOI_REPLACEMENTS = {
    "S006": "S007",
    "S008": "S002",
    "S018": "S079",
    "S027": "S005",
    "S033": "S073",
    "S037": "S077",
    "S038": "S068",
    "S039": "S068",
    "S041": "S065",
    "S044": "S065",
    "S045": "S069",
    "S046": "S069",
    "S048": "S070",
    "S050": "S069",
    "S051": "S069",
    "S053": "S066",
    "S056": "S067",
    "S057": "S066",
    "S061": "S087",
}


REVISED_FINDING_SOURCES = {
    "F01": ("S001", "S002"),
    "F02": ("S005", "S071"),
    "F03": ("S025", "S073"),
    "F04": ("S015", "S016", "S079"),
    "F05": ("S005", "S068"),
    "F06": ("S065", "S068"),
    "F07": ("S065", "S069", "S070"),
    "F08": ("S069", "S070"),
    "F09": ("S071", "S072"),
    "F10": ("S082", "S065"),
    "F11": ("S066", "S067"),
    "F12": ("S071", "S081"),
    "F13": ("S071", "S030"),
    "F14": ("S072", "S074"),
    "F15": ("S070", "S087"),
    "F16": ("S074", "S087", "S088"),
    "F17": ("S058", "S088"),
    "F18": ("S083", "S087"),
    "F19": ("S074", "S088"),
    "F20": ("S060", "S087", "S088"),
    "F21": ("S066", "S087"),
    "F22": ("S058", "S059", "S083"),
    "F23": ("S087", "S088"),
    "F24": ("S007", "S082"),
    "F25": ("S002", "S003", "S030"),
    "F26": ("S007", "S072"),
    "F27": ("S069", "S070"),
    "F28": ("S069", "S070"),
    "F29": ("S030", "S076", "S080", "S084"),
    "F30": ("S002", "S003", "S005", "S028"),
    "F31": ("S030", "S058", "S074"),
    "F32": ("S060", "S087", "S088"),
    "F33": ("S058", "S074", "S088"),
    "F34": ("S058", "S087"),
    "F35": ("S074", "S087", "S088"),
    "F36": ("S058", "S072"),
    "F37": ("S066", "S067"),
    "F38": ("S066", "S067"),
    "F39": ("S065", "S068", "S069"),
    "F40": ("S069", "S070"),
    "F41": ("S066", "S067", "S074"),
}


R71_CLAIM_SOURCES = {
    "R7-C01": ("S066", "S067"),
    "R7-C02": ("S073", "S076", "S084"),
    "R7-C03": ("S001", "S002"),
    "R7-C04": ("S025", "S073"),
    "R7-C05": ("S015", "S016", "S079"),
    "R7-C06": ("S030", "S076", "S084"),
    "R7-C07": ("S065", "S068"),
    "R7-C08": ("S069", "S070"),
    "R7-C09": ("S071", "S081"),
    "R7-C10": ("S070", "S087"),
    "R7-C11": ("S087", "S088"),
    "R7-C12": ("S002", "S007", "S030"),
    "R7-C13": ("S066", "S067"),
    "R7-C14": ("S066", "S067"),
}


def all_sources():
    """Return the original R7 sources plus R7.1 replacement sources."""
    return list(SOURCES) + list(REPLACEMENT_SOURCES)


def all_sources_by_id():
    return {source["source_id"]: source for source in all_sources()}


def final_sources():
    lookup = all_sources_by_id()
    return [lookup[source_id] for source_id in sorted(FINAL_SOURCE_IDS)]


def project_findings_by_id():
    return {finding[0]: finding for finding in PROJECT_FINDINGS}
