"""Curated literature metadata and project mappings for R7.

The entries in this file are manually curated from publisher, index, or
scholarly repository records reviewed during R7. Automated web-search results
are not claimed here; search logs separately record the search systems actually
used.
"""

ACCESS_DATE = "2026-08-04"

DOMAINS = {
    "social_deduction": "Social deduction and hidden-role games",
    "asymmetric_information": "Game theory and asymmetric information",
    "herding_trust": "Herding, trust, and collective decision-making",
    "deception_misinformation": "Misinformation and strategic deception",
    "behavioral_finance": "Behavioral finance and market analogy",
    "bow_domain_shift": "Bag-of-Words, text quantification, and domain shift",
    "offline_policy": "Offline policy evaluation and distribution shift",
    "simulation_validation": "Multi-agent simulation and validation",
    "risk_metrics": "Decision-making and risk metrics",
}


SOURCES = [
    {
        "source_id": "S001",
        "citation_key": "braverman2008mafia",
        "title": "Mafia: A theoretical study of players and coalitions in a partial information environment",
        "authors": "Mark Braverman; Omid Etesami; Elchanan Mossel",
        "year": "2008",
        "venue": "Annals of Applied Probability",
        "doi": "10.1214/07-AAP456",
        "url": "https://doi.org/10.1214/07-AAP456",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "social_deduction",
        "secondary_domains": "asymmetric_information;simulation_validation",
        "relevance": "Formal Mafia model with hidden coalitions, communication, and relative power.",
        "exact_claim_supported": "Mafia/Werewolf is a valid partial-information game model where informed minorities can dominate under low information.",
        "limitations": "Theoretical abstraction differs from this simulator's role actions and speech machinery.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S002",
        "citation_key": "eger2018story",
        "title": "Keeping the Story Straight: A Comparison of Commitment Strategies for a Social Deduction Game",
        "authors": "Markus Eger; Chris Martens",
        "year": "2018",
        "venue": "AAAI Conference on Artificial Intelligence and Interactive Digital Entertainment",
        "doi": "10.1609/aiide.v14i1.13015",
        "url": "https://doi.org/10.1609/aiide.v14i1.13015",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "social_deduction",
        "secondary_domains": "deception_misinformation",
        "relevance": "Studies commitment and deception in One Night Ultimate Werewolf agents.",
        "exact_claim_supported": "Story consistency and deception commitment are central in social deduction agents.",
        "limitations": "One Night Ultimate Werewolf has a shorter horizon than the DURF simulator.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S003",
        "citation_key": "eger2019commitment",
        "title": "A Study of AI Agent Commitment in One Night Ultimate Werewolf with Human Players",
        "authors": "Markus Eger; Chris Martens",
        "year": "2019",
        "venue": "AAAI Conference on Artificial Intelligence and Interactive Digital Entertainment",
        "doi": "10.1609/aiide.v15i1.5236",
        "url": "https://doi.org/10.1609/aiide.v15i1.5236",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "social_deduction",
        "secondary_domains": "deception_misinformation",
        "relevance": "Human-agent social deduction experiment on commitment and player perception.",
        "exact_claim_supported": "Deception policy design involves a tradeoff between consistency, credibility, and performance.",
        "limitations": "Human perception experiment; not directly comparable to automated 10-player Werewolf.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S004",
        "citation_key": "toriumi2017aiwolf",
        "title": "AI Wolf Contest: Development of Game AI Using Collective Intelligence",
        "authors": "Fujio Toriumi; Hirotaka Osawa; Michimasa Inaba; Daisuke Katagami; Kosuke Shinoda; Hitoshi Matsubara",
        "year": "2017",
        "venue": "Communications in Computer and Information Science",
        "doi": "10.1007/978-3-319-57969-6_8",
        "url": "https://doi.org/10.1007/978-3-319-57969-6_8",
        "source_type": "book chapter",
        "peer_reviewed": "yes",
        "domain": "social_deduction",
        "secondary_domains": "simulation_validation",
        "relevance": "Introduces AIWolf as a Werewolf AI platform and competition.",
        "exact_claim_supported": "Werewolf can serve as a benchmark for multi-agent communication, deception, and role inference.",
        "limitations": "Platform and contest design differ from this project's research simulator.",
        "quality_grade": "B",
        "metadata_status": "verified_index_record",
    },
    {
        "source_id": "S005",
        "citation_key": "ibraheem2022con",
        "title": "Putting the Con in Context: Identifying Deceptive Actors in the Game of Mafia",
        "authors": "Samee Ibraheem; Gaoyue Zhou; John DeNero",
        "year": "2022",
        "venue": "NAACL-HLT",
        "doi": "10.18653/v1/2022.naacl-main.11",
        "url": "https://aclanthology.org/2022.naacl-main.11/",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "social_deduction",
        "secondary_domains": "bow_domain_shift;deception_misinformation",
        "relevance": "Text-based Mafia role and deception detection.",
        "exact_claim_supported": "Conversational context helps identify deceptive actors, but deception detection remains hard.",
        "limitations": "Uses human Mafia dialogue, not generated DURF template speech.",
        "quality_grade": "A",
        "metadata_status": "verified_acl_record",
    },
    {
        "source_id": "S006",
        "citation_key": "serrino2019friend",
        "title": "Finding Friend and Foe in Multi-Agent Games",
        "authors": "Jack Serrino; Max Kleiman-Weiner; David C. Parkes; Joshua B. Tenenbaum",
        "year": "2019",
        "venue": "NeurIPS",
        "doi": "",
        "url": "https://arxiv.org/abs/1906.02330",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "social_deduction",
        "secondary_domains": "offline_policy;asymmetric_information",
        "relevance": "DeepRole hidden-role Avalon agent with belief reasoning.",
        "exact_claim_supported": "Hidden-role games require joint belief inference and action-based friend-or-foe reasoning.",
        "limitations": "Avalon action space and no natural-language chat differ from Werewolf speech simulation.",
        "quality_grade": "A",
        "metadata_status": "verified_index_and_arxiv_record",
    },
    {
        "source_id": "S007",
        "citation_key": "stepputtis2023avalon",
        "title": "Long-Horizon Dialogue Understanding for Role Identification in the Game of Avalon with Large Language Models",
        "authors": "Simon Stepputtis; Joseph Campbell; Yaqi Xie; Zhengyang Qi; Wenxin Zhang; Ruiyi Wang; Sanketh Rangreji; Charles Lewis; Katia Sycara",
        "year": "2023",
        "venue": "Findings of EMNLP",
        "doi": "10.18653/v1/2023.findings-emnlp.748",
        "url": "https://aclanthology.org/2023.findings-emnlp.748/",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "social_deduction",
        "secondary_domains": "bow_domain_shift;deception_misinformation",
        "relevance": "Long-horizon deception and role identification in Avalon dialogue.",
        "exact_claim_supported": "Long-horizon dialogue remains difficult for role inference under deception.",
        "limitations": "Small human dataset and Avalon rules limit direct effect-size comparison.",
        "quality_grade": "A",
        "metadata_status": "verified_acl_record",
    },
    {
        "source_id": "S008",
        "citation_key": "kopparapu2022hidden",
        "title": "Hidden Agenda: A Social Deduction Game with Diverse Learned Equilibria",
        "authors": "Kavya Kopparapu; Edgar A. Dueniez-Guzman; Jayd Matyas; Alexander Sasha Vezhnevets; John P. Agapiou; Kevin R. McKee; Richard Everett; Janusz Marecki; Joel Z. Leibo; Thore Graepel",
        "year": "2022",
        "venue": "CoRR",
        "doi": "",
        "url": "https://arxiv.org/abs/2201.01816",
        "source_type": "preprint",
        "peer_reviewed": "no",
        "domain": "social_deduction",
        "secondary_domains": "simulation_validation;offline_policy",
        "relevance": "Learned equilibria in a spatial social deduction environment.",
        "exact_claim_supported": "Social deduction environments can produce diverse learned behavioral regimes.",
        "limitations": "Preprint and non-Werewolf spatial environment; used as background only.",
        "quality_grade": "C",
        "metadata_status": "verified_arxiv_record",
    },
    {
        "source_id": "S009",
        "citation_key": "harsanyi1967bayesian",
        "title": "Games with Incomplete Information Played by Bayesian Players, I-III. Part I. The Basic Model",
        "authors": "John C. Harsanyi",
        "year": "1967",
        "venue": "Management Science",
        "doi": "10.1287/mnsc.14.3.159",
        "url": "https://doi.org/10.1287/mnsc.14.3.159",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "asymmetric_information",
        "secondary_domains": "social_deduction",
        "relevance": "Foundational Bayesian games under incomplete information.",
        "exact_claim_supported": "Hidden-role games can be framed as incomplete-information games with subjective beliefs over types.",
        "limitations": "General theory, not a social-deduction simulation.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S010",
        "citation_key": "akerlof1970lemons",
        "title": "The Market for Lemons: Quality Uncertainty and the Market Mechanism",
        "authors": "George A. Akerlof",
        "year": "1970",
        "venue": "Quarterly Journal of Economics",
        "doi": "10.2307/1879431",
        "url": "https://doi.org/10.2307/1879431",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "asymmetric_information",
        "secondary_domains": "behavioral_finance",
        "relevance": "Canonical asymmetric-information market model.",
        "exact_claim_supported": "Information asymmetry can produce adverse selection and motivates reputation or screening analogies.",
        "limitations": "Market-quality model, not a game of voting or role inference.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S011",
        "citation_key": "spence1973signaling",
        "title": "Job Market Signaling",
        "authors": "Michael Spence",
        "year": "1973",
        "venue": "Quarterly Journal of Economics",
        "doi": "10.2307/1882010",
        "url": "https://doi.org/10.2307/1882010",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "asymmetric_information",
        "secondary_domains": "deception_misinformation;behavioral_finance",
        "relevance": "Foundational signaling model.",
        "exact_claim_supported": "Speech and reveal decisions can be interpreted as signals whose credibility matters.",
        "limitations": "Signaling model is economic and stylized; DURF signals are simulated speech acts.",
        "quality_grade": "A",
        "metadata_status": "verified_index_record",
    },
    {
        "source_id": "S012",
        "citation_key": "crawford1982cheap",
        "title": "Strategic Information Transmission",
        "authors": "Vincent P. Crawford; Joel Sobel",
        "year": "1982",
        "venue": "Econometrica",
        "doi": "10.2307/1913390",
        "url": "https://doi.org/10.2307/1913390",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "asymmetric_information",
        "secondary_domains": "deception_misinformation",
        "relevance": "Canonical cheap-talk model with sender-receiver preference divergence.",
        "exact_claim_supported": "Strategic communication is less informative when preferences diverge, matching wolf deception constraints.",
        "limitations": "Cheap-talk equilibria are not directly estimated in DURF.",
        "quality_grade": "A",
        "metadata_status": "verified_index_record",
    },
    {
        "source_id": "S013",
        "citation_key": "mertens1985beliefs",
        "title": "Formulation of Bayesian Analysis for Games with Incomplete Information",
        "authors": "Jean-Francois Mertens; Shmuel Zamir",
        "year": "1985",
        "venue": "International Journal of Game Theory",
        "doi": "10.1007/BF01770224",
        "url": "https://doi.org/10.1007/BF01770224",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "asymmetric_information",
        "secondary_domains": "social_deduction",
        "relevance": "Formal belief hierarchies for incomplete-information games.",
        "exact_claim_supported": "Beliefs about other players' roles and beliefs are central in hidden-role games.",
        "limitations": "The DURF simulator uses scalar p_wolf rather than full belief hierarchies.",
        "quality_grade": "A",
        "metadata_status": "verified_institutional_record",
    },
    {
        "source_id": "S014",
        "citation_key": "kreps1982sequential",
        "title": "Sequential Equilibria",
        "authors": "David M. Kreps; Robert Wilson",
        "year": "1982",
        "venue": "Econometrica",
        "doi": "10.2307/1912767",
        "url": "https://doi.org/10.2307/1912767",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "asymmetric_information",
        "secondary_domains": "simulation_validation",
        "relevance": "Equilibrium concept for dynamic games with beliefs.",
        "exact_claim_supported": "Dynamic hidden-information settings require belief consistency over histories.",
        "limitations": "DURF validates policy outcomes empirically rather than solving equilibrium.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S015",
        "citation_key": "banerjee1992herd",
        "title": "A Simple Model of Herd Behavior",
        "authors": "Abhijit V. Banerjee",
        "year": "1992",
        "venue": "Quarterly Journal of Economics",
        "doi": "10.2307/2118364",
        "url": "https://doi.org/10.2307/2118364",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "herding_trust",
        "secondary_domains": "behavioral_finance",
        "relevance": "Canonical sequential herding model.",
        "exact_claim_supported": "Social observation can make agents ignore private signals and amplify errors.",
        "limitations": "Sequential adoption model, not simultaneous day voting.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S016",
        "citation_key": "bikhchandani1992cascades",
        "title": "A Theory of Fads, Fashion, Custom, and Cultural Change as Informational Cascades",
        "authors": "Sushil Bikhchandani; David Hirshleifer; Ivo Welch",
        "year": "1992",
        "venue": "Journal of Political Economy",
        "doi": "10.1086/261849",
        "url": "https://doi.org/10.1086/261849",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "herding_trust",
        "secondary_domains": "behavioral_finance",
        "relevance": "Foundational informational-cascade theory.",
        "exact_claim_supported": "Aggregation can produce fragile cascades when public behavior outweighs private information.",
        "limitations": "The DURF herding mechanism is simpler than the formal cascade model.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S017",
        "citation_key": "asch1955pressure",
        "title": "Opinions and Social Pressure",
        "authors": "Solomon E. Asch",
        "year": "1955",
        "venue": "Scientific American",
        "doi": "10.1038/scientificamerican1155-31",
        "url": "https://doi.org/10.1038/scientificamerican1155-31",
        "source_type": "article",
        "peer_reviewed": "no",
        "domain": "herding_trust",
        "secondary_domains": "deception_misinformation",
        "relevance": "Classic conformity experiment summary.",
        "exact_claim_supported": "Group pressure can change individual judgments even when private evidence exists.",
        "limitations": "Psychology demonstration, not a computational model or financial setting.",
        "quality_grade": "B",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S018",
        "citation_key": "surowiecki2004wisdom",
        "title": "The Wisdom of Crowds",
        "authors": "James Surowiecki",
        "year": "2004",
        "venue": "Doubleday",
        "doi": "",
        "url": "https://books.google.com/books?id=Moh1Z6D4VRAC",
        "source_type": "book",
        "peer_reviewed": "no",
        "domain": "herding_trust",
        "secondary_domains": "simulation_validation",
        "relevance": "Popular synthesis of collective intelligence conditions.",
        "exact_claim_supported": "Collective decisions work best when independent information is not collapsed into conformity.",
        "limitations": "Secondary synthesis; not used for formal claims.",
        "quality_grade": "C",
        "metadata_status": "verified_book_record",
    },
    {
        "source_id": "S019",
        "citation_key": "josang2007trust",
        "title": "A Survey of Trust and Reputation Systems for Online Service Provision",
        "authors": "Audun Josang; Roslan Ismail; Colin Boyd",
        "year": "2007",
        "venue": "Decision Support Systems",
        "doi": "10.1016/j.dss.2005.05.019",
        "url": "https://doi.org/10.1016/j.dss.2005.05.019",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "herding_trust",
        "secondary_domains": "deception_misinformation;behavioral_finance",
        "relevance": "Trust/reputation system survey.",
        "exact_claim_supported": "Speaker-specific trust memory is analogous to reputation scores used for later decisions.",
        "limitations": "Online service provision differs from hidden-role games.",
        "quality_grade": "B",
        "metadata_status": "verified_index_record",
    },
    {
        "source_id": "S020",
        "citation_key": "resnick2002trust",
        "title": "Trust Among Strangers in Internet Transactions: Empirical Analysis of eBay's Reputation System",
        "authors": "Paul Resnick; Richard Zeckhauser",
        "year": "2002",
        "venue": "The Economics of the Internet and E-Commerce",
        "doi": "10.1016/S0278-0984(02)11030-3",
        "url": "https://doi.org/10.1016/S0278-0984(02)11030-3",
        "source_type": "book chapter",
        "peer_reviewed": "yes",
        "domain": "herding_trust",
        "secondary_domains": "behavioral_finance",
        "relevance": "Empirical reputation-system evidence.",
        "exact_claim_supported": "Trust records can support transactions among parties with asymmetric information.",
        "limitations": "Reputation is explicit transaction history, not inferred speech reliability.",
        "quality_grade": "B",
        "metadata_status": "verified_dblp_and_author_record",
    },
    {
        "source_id": "S021",
        "citation_key": "dellarocas2005reputation",
        "title": "Reputation Mechanism Design in Online Trading Environments with Pure Moral Hazard",
        "authors": "Chrysanthos Dellarocas",
        "year": "2005",
        "venue": "Information Systems Research",
        "doi": "10.1287/isre.1050.0054",
        "url": "https://doi.org/10.1287/isre.1050.0054",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "herding_trust",
        "secondary_domains": "deception_misinformation;behavioral_finance",
        "relevance": "Reputation design under opportunistic behavior.",
        "exact_claim_supported": "Credibility costs and reputation mechanisms can discipline strategic misbehavior.",
        "limitations": "Pure moral hazard in markets, not public accusations in Werewolf.",
        "quality_grade": "B",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S022",
        "citation_key": "vosoughi2018false",
        "title": "The Spread of True and False News Online",
        "authors": "Soroush Vosoughi; Deb Roy; Sinan Aral",
        "year": "2018",
        "venue": "Science",
        "doi": "10.1126/science.aap9559",
        "url": "https://doi.org/10.1126/science.aap9559",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "deception_misinformation",
        "secondary_domains": "herding_trust",
        "relevance": "Large-scale empirical misinformation diffusion study.",
        "exact_claim_supported": "False information can diffuse differently from true information, motivating credibility controls.",
        "limitations": "Twitter rumor diffusion, not game speech or hidden roles.",
        "quality_grade": "A",
        "metadata_status": "verified_pubmed_record",
    },
    {
        "source_id": "S023",
        "citation_key": "lazer2018science",
        "title": "The Science of Fake News",
        "authors": "David M. J. Lazer; Matthew A. Baum; Yochai Benkler; Adam J. Berinsky; Kelly M. Greenhill; Filippo Menczer; Miriam J. Metzger; Brendan Nyhan; Gordon Pennycook; David Rothschild; Michael Schudson; Steven A. Sloman; Cass R. Sunstein; Emily A. Thorson; Duncan J. Watts; Jonathan L. Zittrain",
        "year": "2018",
        "venue": "Science",
        "doi": "10.1126/science.aao2998",
        "url": "https://doi.org/10.1126/science.aao2998",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "deception_misinformation",
        "secondary_domains": "simulation_validation",
        "relevance": "Research agenda for fake news and interventions.",
        "exact_claim_supported": "Misinformation claims need careful measurement and platform-sensitive interpretation.",
        "limitations": "Broad agenda article rather than direct experiment.",
        "quality_grade": "B",
        "metadata_status": "verified_pubmed_record",
    },
    {
        "source_id": "S024",
        "citation_key": "allcott2017fake",
        "title": "Social Media and Fake News in the 2016 Election",
        "authors": "Hunt Allcott; Matthew Gentzkow",
        "year": "2017",
        "venue": "Journal of Economic Perspectives",
        "doi": "10.1257/jep.31.2.211",
        "url": "https://doi.org/10.1257/jep.31.2.211",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "deception_misinformation",
        "secondary_domains": "behavioral_finance",
        "relevance": "Economic framing of fake news consumption and belief.",
        "exact_claim_supported": "False narratives interact with prior beliefs and network exposure.",
        "limitations": "Election media context, not social deduction.",
        "quality_grade": "B",
        "metadata_status": "verified_aea_record",
    },
    {
        "source_id": "S025",
        "citation_key": "pennycook2019crowd",
        "title": "Fighting Misinformation on Social Media Using Crowdsourced Judgments of News Source Quality",
        "authors": "Gordon Pennycook; David G. Rand",
        "year": "2019",
        "venue": "Proceedings of the National Academy of Sciences",
        "doi": "10.1073/pnas.1806781116",
        "url": "https://doi.org/10.1073/pnas.1806781116",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "deception_misinformation",
        "secondary_domains": "herding_trust",
        "relevance": "Crowd-based source quality judgments against misinformation.",
        "exact_claim_supported": "Reputation-like quality signals can reduce misinformation exposure.",
        "limitations": "Crowd source ratings differ from game-level speaker memory.",
        "quality_grade": "A",
        "metadata_status": "verified_pubmed_record",
    },
    {
        "source_id": "S026",
        "citation_key": "pennycook2021accuracy",
        "title": "Shifting Attention to Accuracy Can Reduce Misinformation Online",
        "authors": "Gordon Pennycook; Ziv Epstein; Mohsen Mosleh; Antonio A. Arechar; Dean Eckles; David G. Rand",
        "year": "2021",
        "venue": "Nature",
        "doi": "10.1038/s41586-021-03344-2",
        "url": "https://doi.org/10.1038/s41586-021-03344-2",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "deception_misinformation",
        "secondary_domains": "herding_trust",
        "relevance": "Intervention that shifts attention toward accuracy.",
        "exact_claim_supported": "Decision environments can alter how much actors weight truth-related signals.",
        "limitations": "Social-media sharing intervention, not voting under hidden roles.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S027",
        "citation_key": "peskov2020lie",
        "title": "It Takes Two to Lie: One to Lie, and One to Listen",
        "authors": "Denis Peskov; Benny Cheng; Ahmed Elgohary; Joe Barrow; Cristian Danescu-Niculescu-Mizil; Jordan Boyd-Graber",
        "year": "2020",
        "venue": "ACL",
        "doi": "",
        "url": "https://aclanthology.org/2020.acl-main.353/",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "deception_misinformation",
        "secondary_domains": "bow_domain_shift;herding_trust",
        "relevance": "Conversation-level deception in Diplomacy.",
        "exact_claim_supported": "Deception depends on both sender and receiver context, supporting speaker-specific trust memory.",
        "limitations": "Diplomacy alliance messaging differs from Werewolf day speech.",
        "quality_grade": "A",
        "metadata_status": "verified_acl_record",
    },
    {
        "source_id": "S028",
        "citation_key": "nguyen2022deceive",
        "title": "When Can the Defender Effectively Deceive Attackers in Security Games?",
        "authors": "Thanh Nguyen; Haifeng Xu",
        "year": "2022",
        "venue": "AAAI",
        "doi": "10.1609/aaai.v36i9.21172",
        "url": "https://doi.org/10.1609/aaai.v36i9.21172",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "deception_misinformation",
        "secondary_domains": "asymmetric_information",
        "relevance": "Formal analysis of deception usefulness and harm under attacker models.",
        "exact_claim_supported": "Deception may be effective or harmful depending on opponent sophistication.",
        "limitations": "Security-game deception differs from wolf daytime deception.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S029",
        "citation_key": "delong1990noise",
        "title": "Noise Trader Risk in Financial Markets",
        "authors": "J. Bradford De Long; Andrei Shleifer; Lawrence H. Summers; Robert J. Waldmann",
        "year": "1990",
        "venue": "Journal of Political Economy",
        "doi": "10.1086/261703",
        "url": "https://doi.org/10.1086/261703",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "herding_trust;risk_metrics",
        "relevance": "Noise trader risk and risk-bearing returns.",
        "exact_claim_supported": "Higher payoff can coexist with higher self-created risk, supporting risk-return framing.",
        "limitations": "Financial asset-price model; DURF payoffs are game utilities.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S030",
        "citation_key": "allen1992manipulation",
        "title": "Stock-Price Manipulation",
        "authors": "Franklin Allen; Douglas Gale",
        "year": "1992",
        "venue": "Review of Financial Studies",
        "doi": "10.1093/rfs/5.3.503",
        "url": "https://doi.org/10.1093/rfs/5.3.503",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "deception_misinformation;asymmetric_information",
        "relevance": "Formal market-manipulation model.",
        "exact_claim_supported": "Manipulators can profit when others attach positive probability to their being informed.",
        "limitations": "Should support only analogy, not causal equivalence with financial markets.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S031",
        "citation_key": "hong1999underreaction",
        "title": "A Unified Theory of Underreaction, Momentum Trading, and Overreaction in Asset Markets",
        "authors": "Harrison Hong; Jeremy C. Stein",
        "year": "1999",
        "venue": "Journal of Finance",
        "doi": "10.1111/0022-1082.00184",
        "url": "https://doi.org/10.1111/0022-1082.00184",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "herding_trust",
        "relevance": "Gradual information diffusion and momentum/overreaction.",
        "exact_claim_supported": "Slow information diffusion can produce momentum and overreaction analogies.",
        "limitations": "Asset pricing is not a direct model of Werewolf voting.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S032",
        "citation_key": "welch1992cascades",
        "title": "Sequential Sales, Learning, and Cascades",
        "authors": "Ivo Welch",
        "year": "1992",
        "venue": "Journal of Finance",
        "doi": "10.1111/j.1540-6261.1992.tb04406.x",
        "url": "https://doi.org/10.1111/j.1540-6261.1992.tb04406.x",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "herding_trust",
        "relevance": "Sequential investor learning and cascades.",
        "exact_claim_supported": "Sequential actions can create cascades and path dependence in market-like settings.",
        "limitations": "IPO sales model; only a conceptual parallel for vote herding.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S033",
        "citation_key": "lakonishok1992institutional",
        "title": "The Impact of Institutional Trading on Stock Prices",
        "authors": "Josef Lakonishok; Andrei Shleifer; Robert W. Vishny",
        "year": "1992",
        "venue": "Journal of Financial Economics",
        "doi": "",
        "url": "https://www.nber.org/papers/w3846",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "herding_trust",
        "relevance": "Empirical analysis of institutional herding and feedback trading.",
        "exact_claim_supported": "Herding claims require empirical validation and can be weaker than expected.",
        "limitations": "NBER page verified; final article metadata requires manual DOI review.",
        "quality_grade": "B",
        "metadata_status": "manual_review_required",
    },
    {
        "source_id": "S034",
        "citation_key": "barberis1998sentiment",
        "title": "A Model of Investor Sentiment",
        "authors": "Nicholas Barberis; Andrei Shleifer; Robert Vishny",
        "year": "1998",
        "venue": "Journal of Financial Economics",
        "doi": "10.1016/S0304-405X(98)00027-0",
        "url": "https://doi.org/10.1016/S0304-405X(98)00027-0",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "risk_metrics",
        "relevance": "Investor sentiment and misreaction model.",
        "exact_claim_supported": "Behavioral biases can produce underreaction and overreaction patterns.",
        "limitations": "General market psychology model, not simulated hidden-role inference.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S035",
        "citation_key": "kyle1985continuous",
        "title": "Continuous Auctions and Insider Trading",
        "authors": "Albert S. Kyle",
        "year": "1985",
        "venue": "Econometrica",
        "doi": "10.2307/1913210",
        "url": "https://doi.org/10.2307/1913210",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "asymmetric_information",
        "relevance": "Canonical informed-trader market model.",
        "exact_claim_supported": "Private information can create an information premium under strategic interaction.",
        "limitations": "Continuous auction model; Seer analogy is conceptual.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S036",
        "citation_key": "grossman1980impossibility",
        "title": "On the Impossibility of Informationally Efficient Markets",
        "authors": "Sanford J. Grossman; Joseph E. Stiglitz",
        "year": "1980",
        "venue": "American Economic Review",
        "doi": "10.2307/1805228",
        "url": "https://doi.org/10.2307/1805228",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "behavioral_finance",
        "secondary_domains": "asymmetric_information",
        "relevance": "Information acquisition and market efficiency theory.",
        "exact_claim_supported": "Useful private information must have value or agents would not acquire it.",
        "limitations": "Market equilibrium result, not direct payoff proof for the Seer.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S037",
        "citation_key": "shiller2000irrational",
        "title": "Irrational Exuberance",
        "authors": "Robert J. Shiller",
        "year": "2000",
        "venue": "Princeton University Press",
        "doi": "",
        "url": "https://press.princeton.edu/books/paperback/9780691173122/irrational-exuberance",
        "source_type": "book",
        "peer_reviewed": "no",
        "domain": "behavioral_finance",
        "secondary_domains": "deception_misinformation;herding_trust",
        "relevance": "Market narratives, contagion, and feedback in speculative behavior.",
        "exact_claim_supported": "Narratives and social transmission can matter in financial behavior analogies.",
        "limitations": "Book-level synthesis; use as conceptual support only.",
        "quality_grade": "B",
        "metadata_status": "manual_review_required",
    },
    {
        "source_id": "S038",
        "citation_key": "manning2008ir",
        "title": "Introduction to Information Retrieval",
        "authors": "Christopher D. Manning; Prabhakar Raghavan; Hinrich Schuetze",
        "year": "2008",
        "venue": "Cambridge University Press",
        "doi": "",
        "url": "https://nlp.stanford.edu/IR-book/",
        "source_type": "book",
        "peer_reviewed": "no",
        "domain": "bow_domain_shift",
        "secondary_domains": "offline_policy",
        "relevance": "Standard reference for text representation and classification.",
        "exact_claim_supported": "Bag-of-Words and sparse text representations are legitimate classical text features.",
        "limitations": "Textbook reference, not evidence for policy value in DURF.",
        "quality_grade": "B",
        "metadata_status": "verified_book_record",
    },
    {
        "source_id": "S039",
        "citation_key": "mccallum1998event",
        "title": "A Comparison of Event Models for Naive Bayes Text Classification",
        "authors": "Andrew McCallum; Kamal Nigam",
        "year": "1998",
        "venue": "AAAI Workshop on Learning for Text Categorization",
        "doi": "",
        "url": "https://aaai.org/papers/041-ws98-05-007/",
        "source_type": "workshop paper",
        "peer_reviewed": "yes",
        "domain": "bow_domain_shift",
        "secondary_domains": "offline_policy",
        "relevance": "Classic comparison of Naive Bayes event models for text.",
        "exact_claim_supported": "Simple BoW event models can be useful but depend on feature and data assumptions.",
        "limitations": "Classification setting, not causal decision integration.",
        "quality_grade": "B",
        "metadata_status": "verified_aaai_record",
    },
    {
        "source_id": "S040",
        "citation_key": "joachims1998text",
        "title": "Text Categorization with Support Vector Machines: Learning with Many Relevant Features",
        "authors": "Thorsten Joachims",
        "year": "1998",
        "venue": "European Conference on Machine Learning",
        "doi": "10.1007/BFb0026683",
        "url": "https://doi.org/10.1007/BFb0026683",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "bow_domain_shift",
        "secondary_domains": "offline_policy",
        "relevance": "Classic sparse high-dimensional text classification method.",
        "exact_claim_supported": "Sparse lexical features can predict labels without guaranteeing decision utility.",
        "limitations": "No direct policy evaluation.",
        "quality_grade": "B",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S041",
        "citation_key": "blitzer2006domain",
        "title": "Domain Adaptation with Structural Correspondence Learning",
        "authors": "John Blitzer; Ryan McDonald; Fernando Pereira",
        "year": "2006",
        "venue": "EMNLP",
        "doi": "",
        "url": "https://aclanthology.org/W06-1615/",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "bow_domain_shift",
        "secondary_domains": "offline_policy",
        "relevance": "NLP domain adaptation under train/test mismatch.",
        "exact_claim_supported": "NLP systems trained in one domain can fail or need adaptation in another.",
        "limitations": "General NLP domain adaptation, not Werewolf templates.",
        "quality_grade": "A",
        "metadata_status": "verified_acl_record",
    },
    {
        "source_id": "S042",
        "citation_key": "bendavid2010domain",
        "title": "A Theory of Learning from Different Domains",
        "authors": "Shai Ben-David; John Blitzer; Koby Crammer; Alex Kulesza; Fernando Pereira; Jennifer Wortman Vaughan",
        "year": "2010",
        "venue": "Machine Learning",
        "doi": "10.1007/s10994-009-5152-4",
        "url": "https://doi.org/10.1007/s10994-009-5152-4",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "bow_domain_shift",
        "secondary_domains": "offline_policy",
        "relevance": "Theory of domain divergence and adaptation.",
        "exact_claim_supported": "Held-out template failure is consistent with domain-shift theory.",
        "limitations": "Theory does not specify DURF template generators.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S043",
        "citation_key": "torralba2011bias",
        "title": "Unbiased Look at Dataset Bias",
        "authors": "Antonio Torralba; Alexei A. Efros",
        "year": "2011",
        "venue": "CVPR",
        "doi": "10.1109/CVPR.2011.5995347",
        "url": "https://doi.org/10.1109/CVPR.2011.5995347",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "bow_domain_shift",
        "secondary_domains": "simulation_validation",
        "relevance": "Dataset bias and cross-dataset generalization.",
        "exact_claim_supported": "Predictive performance can be dataset-bound and fail under distribution shift.",
        "limitations": "Computer vision setting; used for methodological analogy.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S044",
        "citation_key": "koh2021wilds",
        "title": "WILDS: A Benchmark of in-the-Wild Distribution Shifts",
        "authors": "Pang Wei Koh; Shiori Sagawa; Henrik Marklund; Sang Michael Xie; Marvin Zhang; Akshay Balsubramani; Weihua Hu; Michihiro Yasunaga; Richard Lanas Phillips; Irena Gao; Tony Lee; Etienne David; Ian Stavness; Wei Guo; Berton Earnshaw; Imran Haque; Sara Beery; Jure Leskovec; Anshul Kundaje; Emma Pierson; Sergey Levine; Chelsea Finn; Percy Liang",
        "year": "2021",
        "venue": "ICML",
        "doi": "",
        "url": "https://proceedings.mlr.press/v139/koh21a.html",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "bow_domain_shift",
        "secondary_domains": "offline_policy",
        "relevance": "Benchmarking real distribution shifts.",
        "exact_claim_supported": "Robustness should be evaluated under grouped or distribution-shifted splits.",
        "limitations": "Benchmark suite, not a Werewolf experiment.",
        "quality_grade": "A",
        "metadata_status": "manual_review_required",
    },
    {
        "source_id": "S045",
        "citation_key": "precup2000offpolicy",
        "title": "Eligibility Traces for Off-Policy Policy Evaluation",
        "authors": "Doina Precup; Richard S. Sutton; Satinder Singh",
        "year": "2000",
        "venue": "ICML",
        "doi": "",
        "url": "https://dblp.org/rec/conf/icml/PrecupSS00",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "offline_policy",
        "secondary_domains": "simulation_validation",
        "relevance": "Early off-policy evaluation under behavior-policy mismatch.",
        "exact_claim_supported": "Evaluating a policy from data generated by another policy requires correction and care.",
        "limitations": "Tabular RL setting, not complete-game Werewolf rollout.",
        "quality_grade": "B",
        "metadata_status": "manual_review_required",
    },
    {
        "source_id": "S046",
        "citation_key": "dudik2011doubly",
        "title": "Doubly Robust Policy Evaluation and Learning",
        "authors": "Miroslav Dudik; John Langford; Lihong Li",
        "year": "2011",
        "venue": "ICML",
        "doi": "",
        "url": "https://www.microsoft.com/en-us/research/publication/doubly-robust-policy-evaluation-and-learning-2/",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "offline_policy",
        "secondary_domains": "risk_metrics",
        "relevance": "Doubly robust contextual-bandit evaluation.",
        "exact_claim_supported": "Offline policy estimates can be biased or high variance without appropriate estimators.",
        "limitations": "DURF uses matched live validation rather than DR estimators.",
        "quality_grade": "A",
        "metadata_status": "verified_research_page",
    },
    {
        "source_id": "S047",
        "citation_key": "thomas2015hcope",
        "title": "High-Confidence Off-Policy Evaluation",
        "authors": "Philip Thomas; Georgios Theocharous; Mohammad Ghavamzadeh",
        "year": "2015",
        "venue": "AAAI",
        "doi": "10.1609/aaai.v29i1.9541",
        "url": "https://doi.org/10.1609/aaai.v29i1.9541",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "offline_policy",
        "secondary_domains": "risk_metrics",
        "relevance": "High-confidence evaluation before deploying policies.",
        "exact_claim_supported": "Unsafe policies should not be deployed based only on weak offline estimates.",
        "limitations": "Confidence-bound method not implemented directly in DURF.",
        "quality_grade": "A",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S048",
        "citation_key": "jiang2016doubly",
        "title": "Doubly Robust Off-policy Value Evaluation for Reinforcement Learning",
        "authors": "Nan Jiang; Lihong Li",
        "year": "2016",
        "venue": "ICML",
        "doi": "",
        "url": "https://proceedings.mlr.press/v48/jiang16.html",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "offline_policy",
        "secondary_domains": "risk_metrics",
        "relevance": "Sequential off-policy value evaluation.",
        "exact_claim_supported": "Sequential policy evaluation has bias-variance tradeoffs and can be hard.",
        "limitations": "Not a direct model of the project's shadow rollout diagnostics.",
        "quality_grade": "A",
        "metadata_status": "verified_pmlr_record",
    },
    {
        "source_id": "S049",
        "citation_key": "li2011unbiased",
        "title": "Unbiased Offline Evaluation of Contextual-Bandit-Based News Article Recommendation Algorithms",
        "authors": "Lihong Li; Wei Chu; John Langford; Xuanhui Wang",
        "year": "2011",
        "venue": "WSDM",
        "doi": "10.1145/1935826.1935878",
        "url": "https://doi.org/10.1145/1935826.1935878",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "offline_policy",
        "secondary_domains": "bow_domain_shift",
        "relevance": "Offline evaluation with logged bandit feedback.",
        "exact_claim_supported": "Logged-data policy evaluation depends on support and logging-policy assumptions.",
        "limitations": "Bandit feedback differs from long-horizon Werewolf games.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S050",
        "citation_key": "levine2020offline",
        "title": "Offline Reinforcement Learning: Tutorial, Review, and Perspectives on Open Problems",
        "authors": "Sergey Levine; Aviral Kumar; George Tucker; Justin Fu",
        "year": "2020",
        "venue": "arXiv",
        "doi": "",
        "url": "https://arxiv.org/abs/2005.01643",
        "source_type": "preprint",
        "peer_reviewed": "no",
        "domain": "offline_policy",
        "secondary_domains": "simulation_validation",
        "relevance": "Review of offline RL and distributional issues.",
        "exact_claim_supported": "Offline RL faces extrapolation and deployment-risk problems.",
        "limitations": "Preprint review; use as background only.",
        "quality_grade": "C",
        "metadata_status": "manual_review_required",
    },
    {
        "source_id": "S051",
        "citation_key": "fujimoto2019bcq",
        "title": "Off-Policy Deep Reinforcement Learning without Exploration",
        "authors": "Scott Fujimoto; David Meger; Doina Precup",
        "year": "2019",
        "venue": "ICML",
        "doi": "",
        "url": "https://proceedings.mlr.press/v97/fujimoto19a.html",
        "source_type": "conference paper",
        "peer_reviewed": "yes",
        "domain": "offline_policy",
        "secondary_domains": "simulation_validation",
        "relevance": "Offline deep RL with support constraints.",
        "exact_claim_supported": "Offline policies can exploit unsupported actions unless constrained.",
        "limitations": "Continuous-control benchmark, not social-deduction policy.",
        "quality_grade": "A",
        "metadata_status": "manual_review_required",
    },
    {
        "source_id": "S052",
        "citation_key": "schelling1971segregation",
        "title": "Dynamic Models of Segregation",
        "authors": "Thomas C. Schelling",
        "year": "1971",
        "venue": "Journal of Mathematical Sociology",
        "doi": "10.1080/0022250X.1971.9989794",
        "url": "https://doi.org/10.1080/0022250X.1971.9989794",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "simulation_validation",
        "secondary_domains": "herding_trust",
        "relevance": "Classic agent-based social process model.",
        "exact_claim_supported": "Simple local rules can generate emergent social patterns.",
        "limitations": "Segregation model, not hidden-role game.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S053",
        "citation_key": "epstein1996growing",
        "title": "Growing Artificial Societies: Social Science from the Bottom Up",
        "authors": "Joshua M. Epstein; Robert Axtell",
        "year": "1996",
        "venue": "Brookings Institution Press",
        "doi": "",
        "url": "https://www.brookings.edu/books/growing-artificial-societies/",
        "source_type": "book",
        "peer_reviewed": "no",
        "domain": "simulation_validation",
        "secondary_domains": "herding_trust",
        "relevance": "Foundational agent-based modeling book.",
        "exact_claim_supported": "Agent-based models can build macro patterns from micro rules.",
        "limitations": "General ABM reference, not a validation method by itself.",
        "quality_grade": "B",
        "metadata_status": "manual_review_required",
    },
    {
        "source_id": "S054",
        "citation_key": "grimm2006odd",
        "title": "A Standard Protocol for Describing Individual-Based and Agent-Based Models",
        "authors": "Volker Grimm; Uta Berger; Finn Bastiansen; Sigrunn Eliassen; Vincent Ginot; Jarl Giske; John Goss-Custard; Tamara Grand; Simone K. Heinz; Geir Huse; Andreas Huth; Jane U. Jepsen; Christian Jorgensen; Wolf M. Mooij; Birgit Mueller; Guy Pe'er; Cyril Piou; Steven F. Railsback; Andrew M. Robbins; Martha M. Robbins; Eva Rossmanith; Nadja Rueger; Espen Strand; Sami Souissi; Richard A. Stillman; Rune Vabo; Ute Visser; Donald L. DeAngelis",
        "year": "2006",
        "venue": "Ecological Modelling",
        "doi": "10.1016/j.ecolmodel.2006.04.023",
        "url": "https://doi.org/10.1016/j.ecolmodel.2006.04.023",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "simulation_validation",
        "secondary_domains": "source_traceability",
        "relevance": "ODD protocol for ABM documentation.",
        "exact_claim_supported": "Simulator mechanisms should be documented with explicit entities, rules, and process overview.",
        "limitations": "Ecological ABM origin, not game-specific.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S055",
        "citation_key": "sargent2013verification",
        "title": "Verification and Validation of Simulation Models",
        "authors": "Robert G. Sargent",
        "year": "2013",
        "venue": "Journal of Simulation",
        "doi": "10.1057/jos.2012.20",
        "url": "https://doi.org/10.1057/jos.2012.20",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "simulation_validation",
        "secondary_domains": "offline_policy",
        "relevance": "Simulation verification and validation framework.",
        "exact_claim_supported": "DURF engine symmetry, replay, and validation tests are necessary model-credibility evidence.",
        "limitations": "General simulation V&V, not specific to social deduction.",
        "quality_grade": "A",
        "metadata_status": "verified_index_record",
    },
    {
        "source_id": "S056",
        "citation_key": "railsback2019abm",
        "title": "Agent-Based and Individual-Based Modeling: A Practical Introduction",
        "authors": "Steven F. Railsback; Volker Grimm",
        "year": "2019",
        "venue": "Princeton University Press",
        "doi": "",
        "url": "https://www.railsback-grimm-abm-book.com/",
        "source_type": "book",
        "peer_reviewed": "no",
        "domain": "simulation_validation",
        "secondary_domains": "source_traceability",
        "relevance": "Practical ABM design, testing, and robustness reference.",
        "exact_claim_supported": "ABM projects should use explicit design, testing, sensitivity, and documentation workflows.",
        "limitations": "Textbook; not direct evidence for Werewolf outcomes.",
        "quality_grade": "B",
        "metadata_status": "verified_book_record",
    },
    {
        "source_id": "S057",
        "citation_key": "law2015simulation",
        "title": "Simulation Modeling and Analysis",
        "authors": "Averill M. Law",
        "year": "2015",
        "venue": "McGraw-Hill",
        "doi": "",
        "url": "https://www.mheducation.com/highered/product/simulation-modeling-analysis-law",
        "source_type": "book",
        "peer_reviewed": "no",
        "domain": "simulation_validation",
        "secondary_domains": "risk_metrics",
        "relevance": "Simulation input, output, validation, and experimental design reference.",
        "exact_claim_supported": "Simulation studies need explicit replication, validation, and output analysis.",
        "limitations": "General simulation methods textbook.",
        "quality_grade": "B",
        "metadata_status": "verified_publisher_record",
    },
    {
        "source_id": "S058",
        "citation_key": "sharpe1966mutual",
        "title": "Mutual Fund Performance",
        "authors": "William F. Sharpe",
        "year": "1966",
        "venue": "Journal of Business",
        "doi": "10.1086/294846",
        "url": "https://doi.org/10.1086/294846",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "risk_metrics",
        "secondary_domains": "behavioral_finance",
        "relevance": "Foundational risk-adjusted performance measure.",
        "exact_claim_supported": "Sharpe-like ratios are a recognized way to compare mean return per unit volatility.",
        "limitations": "DURF payoff ratios are analogues and not investment returns.",
        "quality_grade": "A",
        "metadata_status": "verified_index_record",
    },
    {
        "source_id": "S059",
        "citation_key": "sortino1994downside",
        "title": "Performance Measurement in a Downside Risk Framework",
        "authors": "Frank A. Sortino; Lee N. Price",
        "year": "1994",
        "venue": "Journal of Investing",
        "doi": "10.3905/joi.3.3.59",
        "url": "https://doi.org/10.3905/joi.3.3.59",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "risk_metrics",
        "secondary_domains": "behavioral_finance",
        "relevance": "Downside-risk performance measurement.",
        "exact_claim_supported": "Sortino-like ratios isolate downside deviation rather than total volatility.",
        "limitations": "Project payoff denominators are game-specific.",
        "quality_grade": "A",
        "metadata_status": "verified_index_record",
    },
    {
        "source_id": "S060",
        "citation_key": "rockafellar2000cvar",
        "title": "Optimization of Conditional Value-at-Risk",
        "authors": "R. Tyrrell Rockafellar; Stanislav Uryasev",
        "year": "2000",
        "venue": "Journal of Risk",
        "doi": "10.21314/JOR.2000.038",
        "url": "https://doi.org/10.21314/JOR.2000.038",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "risk_metrics",
        "secondary_domains": "behavioral_finance",
        "relevance": "CVaR optimization reference.",
        "exact_claim_supported": "Tail-risk metrics should examine expected losses conditional on bad outcomes.",
        "limitations": "Optimization framework, while DURF reports CVaR-like descriptive metrics.",
        "quality_grade": "A",
        "metadata_status": "verified_index_record",
    },
    {
        "source_id": "S061",
        "citation_key": "jorion2007var",
        "title": "Value at Risk: The New Benchmark for Managing Financial Risk",
        "authors": "Philippe Jorion",
        "year": "2007",
        "venue": "McGraw-Hill",
        "doi": "",
        "url": "https://www.mheducation.com/",
        "source_type": "book",
        "peer_reviewed": "no",
        "domain": "risk_metrics",
        "secondary_domains": "behavioral_finance",
        "relevance": "Value-at-risk risk-management reference.",
        "exact_claim_supported": "VaR-like metrics summarize percentile tail exposure.",
        "limitations": "Book metadata requires manual edition review; used for conceptual metric framing.",
        "quality_grade": "B",
        "metadata_status": "manual_review_required",
    },
    {
        "source_id": "S062",
        "citation_key": "markowitz1952portfolio",
        "title": "Portfolio Selection",
        "authors": "Harry Markowitz",
        "year": "1952",
        "venue": "Journal of Finance",
        "doi": "10.2307/2975974",
        "url": "https://doi.org/10.2307/2975974",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "risk_metrics",
        "secondary_domains": "behavioral_finance",
        "relevance": "Mean-variance portfolio theory.",
        "exact_claim_supported": "Risk-return tradeoffs are a formal basis for strategy frontier analogies.",
        "limitations": "Portfolio optimization is not equivalent to role selection in a game.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S063",
        "citation_key": "artzner1999coherent",
        "title": "Coherent Measures of Risk",
        "authors": "Philippe Artzner; Freddy Delbaen; Jean-Marc Eber; David Heath",
        "year": "1999",
        "venue": "Mathematical Finance",
        "doi": "10.1111/1467-9965.00068",
        "url": "https://doi.org/10.1111/1467-9965.00068",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "risk_metrics",
        "secondary_domains": "behavioral_finance",
        "relevance": "Coherent risk measure axioms.",
        "exact_claim_supported": "Risk metrics require explicit definitions and caveats about what properties they satisfy.",
        "limitations": "DURF VaR/CVaR-like metrics are descriptive analogues, not full coherent-risk optimization.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
    {
        "source_id": "S064",
        "citation_key": "kahneman1979prospect",
        "title": "Prospect Theory: An Analysis of Decision under Risk",
        "authors": "Daniel Kahneman; Amos Tversky",
        "year": "1979",
        "venue": "Econometrica",
        "doi": "10.2307/1914185",
        "url": "https://doi.org/10.2307/1914185",
        "source_type": "journal article",
        "peer_reviewed": "yes",
        "domain": "risk_metrics",
        "secondary_domains": "behavioral_finance",
        "relevance": "Behavioral decision-making under risk.",
        "exact_claim_supported": "Risk preferences can alter choices and payoff distributions.",
        "limitations": "The project's risk-preference labels are simplified and not calibrated prospect-theory parameters.",
        "quality_grade": "A",
        "metadata_status": "manual_identifier_review",
    },
]


SEARCH_LOGS = [
    ("R7-S01", "Codex web search", "Mafia theoretical study partial information environment DOI", "social_deduction", "12", "3", "retained Werewolf/Mafia theory and AI sources"),
    ("R7-S02", "AAAI OJS", "Werewolf social deduction commitment strategies", "social_deduction", "4", "2", "retained peer-reviewed AIIDE Werewolf papers"),
    ("R7-S03", "ACL Anthology", "Mafia Avalon deception role identification dialogue", "social_deduction", "5", "3", "retained Mafia/Avalon dialogue papers"),
    ("R7-S04", "Codex web search", "Harsanyi Spence Crawford Sobel Akerlof DOI", "asymmetric_information", "12", "6", "retained canonical information economics sources"),
    ("R7-S05", "Codex web search", "Banerjee Bikhchandani herding informational cascades DOI", "herding_trust", "12", "5", "retained herding and trust records"),
    ("R7-S06", "PubMed and publisher records", "fake news misinformation spread credibility DOI", "deception_misinformation", "12", "5", "retained misinformation and accuracy-intervention sources"),
    ("R7-S07", "Codex web search", "market manipulation noise trader risk herding finance DOI", "behavioral_finance", "12", "8", "retained financial-market analogy sources"),
    ("R7-S08", "ACL Anthology and publisher pages", "bag of words domain adaptation dataset bias text classification", "bow_domain_shift", "12", "7", "retained BoW and domain-shift sources"),
    ("R7-S09", "PMLR, AAAI OJS, Microsoft Research", "off-policy evaluation distribution shift doubly robust policy", "offline_policy", "12", "7", "retained OPE and offline RL sources"),
    ("R7-S10", "Publisher and book pages", "agent-based simulation verification validation ODD protocol", "simulation_validation", "12", "6", "retained ABM and simulation V&V sources"),
    ("R7-S11", "Publisher and index records", "Sharpe Sortino VaR CVaR portfolio risk DOI", "risk_metrics", "12", "7", "retained risk metric sources"),
]


def source_by_id():
    return {source["source_id"]: source for source in SOURCES}


PROJECT_FINDINGS = [
    ("F01", "low_information_baseline", "Low-information village performance was weak.", "Stage 1 random baseline reported very high wolf win.", "LEVEL 1 - descriptive pilot", "S001;S009;S010", "consistent_with_literature", "Low-information hidden-role environments favor the informed minority."),
    ("F02", "information_and_speech", "Structured speech substantially improved village outcomes.", "Stage 2 speech-enabled village win improved descriptively.", "LEVEL 1 - descriptive pilot", "S005;S011;S019", "consistent_with_literature", "Communication can transmit useful signals when credibility is bounded."),
    ("F03", "villager_strategy", "Trust-weighted voting was the strongest tested Villager policy.", "R6.1 Villager trust_weighted had best mean actor payoff.", "LEVEL 4 - matched live validation pilot", "S019;S020;S021;S025", "consistent_with_literature", "Reputation-weighted aggregation parallels trust and reputation systems."),
    ("F04", "herding", "Unconditional or poorly calibrated aggregation may amplify error.", "Trust-weighted herding was non-monotonic and not uniformly beneficial.", "LEVEL 2 - replicated descriptive experiment", "S015;S016;S017", "consistent_with_literature", "Cascades and conformity can propagate wrong signals."),
    ("F05", "bow_r2", "BoW had moderate held-out predictive value.", "R2 BoW-score speaker-is-wolf AUC was 0.692.", "LEVEL 3 - formal validation design", "S038;S039;S040", "methodological_parallel", "Sparse lexical features can carry predictive signal."),
    ("F06", "bow_r2", "BoW failed under unseen templates.", "Full BoW vector AUC dropped under OOD-template split.", "LEVEL 3 - formal validation design", "S041;S042;S043;S044", "consistent_with_literature", "Template failure is a domain-shift problem."),
    ("F07", "bow_r3", "Live BoW integration reduced village outcomes.", "R3 guarded BoW live policies underperformed reference conditions.", "LEVEL 3 - formal validation design", "S041;S046;S047;S048", "consistent_with_literature", "Prediction quality need not translate into policy value."),
    ("F08", "ml_policy", "Prediction quality did not imply policy value.", "ML shadow improvements did not survive matched live validation.", "LEVEL 4 - robustness-validated", "S046;S047;S048;S049;S050", "consistent_with_literature", "Offline or surrogate evaluation can fail under live distribution shift."),
    ("F09", "seer_information", "Early wolf discovery was associated with village success.", "Structured search diagnostics found positive information-discovery indicators.", "LEVEL 4 - robustness-validated", "S009;S035;S036", "consistent_with_literature", "Private information can have strategic value."),
    ("F10", "seer_search", "Highest-suspicion and highest-p_wolf checking were not supported.", "Both were harmful versus random in structured seer search.", "LEVEL 4 - robustness-validated", "S042;S043;S055", "extends_literature", "Local risk scores can be post-treatment or misleading if not calibrated."),
    ("F11", "position_theory", "Position folklore was not supported after randomization.", "Edge seats were not wolf-heavy and edge-first did not beat random.", "LEVEL 3 - formal statistical analysis", "S055;S057", "methodological_parallel", "Randomized assignment and validation can falsify intuitive artifacts."),
    ("F12", "seer_reveal", "Immediate reveal was promising but uncertain.", "R6.1 immediate_reveal had best Seer mean payoff but pilot caveats remain.", "LEVEL 4 - matched live validation pilot", "S011;S012;S035", "partially_consistent", "Information revelation has benefits and strategic costs."),
    ("F13", "seer_reveal", "Reveal generated high short-term mortality hazard.", "R6.2 corrected Seer survival with post-reveal hazard metrics.", "LEVEL 4 - matched supplementary metric audit", "S011;S030;S035", "extends_literature", "Public signalers can become strategic targets."),
    ("F14", "risk_metrics", "Information premium was positive but partly outcome-dependent.", "R5 information premium was positive but sensitive to outcome conditioning.", "LEVEL 4 - risk-analysis", "S036;S058;S060", "partially_consistent", "Information value should be separated from outcome dependence."),
    ("F15", "witch", "Aggressive intervention had a possible return advantage.", "R6.1 Witch aggressive_full had best mean actor payoff.", "LEVEL 4 - matched live validation pilot", "S047;S057;S064", "methodological_parallel", "High-impact interventions can raise expected value but require risk controls."),
    ("F16", "witch", "Aggressive intervention increased wrong-poison risk.", "R6.2 lifecycle metrics separate wrong poison from true waste.", "LEVEL 4 - metric audit", "S060;S063;S064", "consistent_with_literature", "Downside/tail metrics clarify intervention harm."),
    ("F17", "witch", "Extreme conservatism produced high unused-resource cost.", "R6.2 measured unused potion and missed opportunities.", "LEVEL 4 - metric audit", "S058;S060;S061", "extends_literature", "Opportunity-cost framing explains excessive inaction."),
    ("F18", "witch", "Conservative-full policy was harmful.", "R6/R6.1 rejected conservative-full-style Witch policy.", "LEVEL 4 - matched live validation pilot", "S057;S064", "partially_consistent", "Risk aversion can be harmful when resources expire unused."),
    ("F19", "witch", "Risk-balanced policies reduced direct waste but did not prove superior.", "R6.2 distinguishes waste categories from win-rate superiority.", "LEVEL 4 - metric audit", "S060;S063", "consistent_with_literature", "Lower risk is not automatically higher payoff."),
    ("F20", "hunter", "Hunter had severe downside and CVaR-like risk.", "R5/R6.1 show Hunter tail risk and uncertain policy improvement.", "LEVEL 4 - risk-analysis", "S060;S061;S063", "consistent_with_literature", "Irreversible high-impact actions concentrate downside risk."),
    ("F21", "hunter", "Random shooting underperformed.", "R6.1 Hunter random shot did not beat reference.", "LEVEL 4 - matched live validation pilot", "S055;S057;S064", "consistent_with_literature", "Uninformed high-impact actions can be dominated by more conservative rules."),
    ("F22", "hunter", "No-shot and conservative-threshold policies were harmful.", "R6.1 found no-shot/conservative policies weak or harmful.", "LEVEL 4 - matched live validation pilot", "S058;S060;S064", "partially_consistent", "Avoiding downside can also forgo positive option value."),
    ("F23", "hunter", "Reference/highest-suspicion-equivalent behavior remained strongest tested.", "R6.1 Hunter reference had best mean payoff.", "LEVEL 4 - matched live validation pilot", "S019;S060", "no_direct_prior_comparison", "No direct prior Hunter policy literature was identified."),
    ("F24", "werewolf_strategy", "Random killing was harmful relative to reference.", "R5.1/R6 found random wolf kills harmful.", "LEVEL 4 - matched live validation pilot", "S006;S009;S055", "consistent_with_literature", "Strategic targeting matters in hidden-role games."),
    ("F25", "werewolf_strategy", "Deep-cover policy was harmful.", "R6.1 deep-cover wolf preset underperformed reference.", "LEVEL 4 - matched live validation pilot", "S002;S003;S030", "partially_consistent", "Concealment is useful only when it does not sacrifice strategic pressure."),
    ("F26", "werewolf_strategy", "Threat-adaptive/reference strategy remained strongest tested.", "R6.1 Werewolf reference had best mean actor payoff.", "LEVEL 4 - matched live validation pilot", "S006;S030;S035", "consistent_with_literature", "Informed actors benefit from targeting high-value information sources."),
    ("F27", "ml_policy", "Continuous ML night-kill control underperformed.", "Stage 2A/2B live ML policies underperformed existing rule.", "LEVEL 4 - formal live validation", "S047;S048;S050;S051", "consistent_with_literature", "Offline policies can fail when rolled out repeatedly."),
    ("F28", "ml_policy", "Hybrid ML was harmful.", "Stage 2A hybrid was statistically harmful after Holm correction.", "LEVEL 4 - formal live validation", "S047;S050;S051", "consistent_with_literature", "Combining model and rule scores can be unsafe without live validation."),
    ("F29", "werewolf_deception", "Manipulation premium was descriptively large but badly imbalanced.", "R5/R5.1 manipulation premium positive but sample-imbalanced.", "LEVEL 4 - risk-analysis", "S030;S022;S024", "partially_consistent", "Manipulation can pay, but evidence quality depends on sample balance."),
    ("F30", "werewolf_deception", "Deception subtype effects differed substantially.", "False accusation, deflection, role claim, and adaptive policy differed sharply.", "LEVEL 2 - diagnostic", "S002;S003;S027;S028", "consistent_with_literature", "Deception effectiveness depends on type, credibility, and audience."),
    ("F31", "financial_risk", "Werewolves had the highest mean and risk-adjusted payoff.", "R5 role-level risk metrics favored Werewolf.", "LEVEL 4 - risk-analysis", "S029;S030;S058;S059", "methodological_parallel", "High return can accompany high strategic risk in a payoff analogue."),
    ("F32", "financial_risk", "Hunter had the worst tail risk.", "R5 CVaR-like metrics identified Hunter tail exposure.", "LEVEL 4 - risk-analysis", "S060;S061;S063", "consistent_with_literature", "Tail-risk metrics reveal harms hidden by means."),
    ("F33", "financial_risk", "Highest expected payoff also had highest risk-adjusted payoff in current design.", "R5 found Werewolf high mean and high Sharpe/Sortino-like ratios.", "LEVEL 4 - risk-analysis", "S058;S059;S062", "methodological_parallel", "Efficient-frontier analogies compare return against volatility and downside risk."),
    ("F34", "financial_risk", "Some low-volatility roles still had negative expected payoff.", "R5 shows volatility alone does not imply desirability.", "LEVEL 4 - risk-analysis", "S058;S060;S063", "consistent_with_literature", "Risk metrics must be interpreted with expected payoff."),
    ("F35", "financial_risk", "Risk-return conclusions depended partly on payoff specification.", "R5 sensitivity produced some fragile ranks.", "LEVEL 4 - sensitivity", "S063;S057", "consistent_with_literature", "Metric definitions and coefficients affect rankings."),
    ("F36", "financial_risk", "Opportunity cost clarified conservative-strategy weaknesses.", "R4/R5 opportunity-cost terms clarified unused resources.", "LEVEL 4 - payoff analysis", "S058;S062;S064", "methodological_parallel", "Opportunity cost links inaction to forgone return."),
    ("F37", "engine_validity", "Seat-label artifacts disappeared under neutral mode.", "Seat-order-neutral rows matched across label transforms.", "LEVEL 5 - engine/design validated", "S055;S057", "consistent_with_literature", "Simulation validation should isolate artifacts."),
    ("F38", "engine_validity", "Physical-direction replay achieved exact symmetry.", "Supplied-action replay and mirror validation had zero divergences.", "LEVEL 5 - engine/design validated", "S055;S057", "consistent_with_literature", "Replay and counterfactual validation increase engine credibility."),
    ("F39", "ml_validation", "Grouped ML validation corrected optimistic pilot performance.", "Stage 1.5 reduced pilot AUC substantially.", "LEVEL 3 - formal validation design", "S042;S043;S044;S050", "consistent_with_literature", "Grouped validation controls overfitting and dataset leakage."),
    ("F40", "ml_validation", "Shadow or surrogate benefits failed to generalize to live policy.", "Stage 2A/2B live tests overturned shadow gains.", "LEVEL 4 - formal live validation", "S046;S047;S048;S049;S050", "consistent_with_literature", "Offline-to-online gaps require live validation."),
    ("F41", "method_validity", "Strategy ownership had to be separated from cross-role externalities.", "R5.1 corrected global strategy labels into actor-specific attribution.", "LEVEL 4 - attribution audit", "S055;S057;S063", "methodological_parallel", "Attribution units and independent samples must match claims."),
]


FINANCIAL_CROSSWALK = [
    ("Villager", "retail investor", "S024;S029;S037", "limited information and vulnerability to narratives", "Villagers vote to eliminate roles; investors allocate capital", "Use as a bounded analogy for uninformed decision makers", "Do not claim villagers literally model retail investors"),
    ("Seer", "informed trader / analyst", "S035;S036;S011", "private signal acquisition and disclosure timing", "Seer information is true role identity, unlike noisy market research", "Information premium is a game payoff analogue", "Do not claim insider-trading equivalence"),
    ("Witch", "regulator / intervention authority", "S047;S060;S063", "rare intervention with false-positive and false-negative costs", "Witch is a player with team incentives, unlike external regulators", "Potion use illustrates intervention timing and waste", "Do not infer policy-regulation conclusions"),
    ("Hunter", "leveraged or high-impact actor", "S060;S061;S064", "irreversible action with tail-risk concentration", "Hunter death shot is discrete and game-rule bounded", "Useful for explaining downside risk", "Do not call Hunter a financial instrument"),
    ("Werewolf", "market manipulator", "S030;S022;S024", "strategic misinformation and exploitation of trust", "Werewolves have hidden team identity and terminal win conditions", "Manipulation premium is conceptual and game-specific", "Do not claim causal market manipulation evidence"),
    ("public speech", "market narrative / disclosure", "S011;S012;S037", "signals shape beliefs and later actions", "Speech is generated in a controlled template system", "Use as a narrative-signal analogy", "Do not equate template speech with natural market news"),
    ("false accusation", "false rumor or misleading signal", "S022;S023;S024", "false claims can alter beliefs and cascade", "Accusations are game-targeted and immediately logged", "Use to illustrate adversarial communication", "Do not imply real rumor law or regulation"),
    ("trust score", "reputation or signal credibility", "S019;S020;S021;S025", "past reliability changes future influence", "Trust scores are symmetric model variables, not human reputation", "Speaker memory maps to reputation-weighted aggregation", "Do not overclaim psychological realism"),
    ("herding", "correlated investor behavior", "S015;S016;S032;S033", "public action can override private signal", "DURF votes are eliminations, not trades", "Use for information-cascade mechanics", "Do not claim observed market herding"),
    ("reveal timing", "information disclosure timing", "S011;S035;S036", "timing changes signal value and exposure", "Seer reveal may provoke night kill", "Frame as information-release timing tradeoff", "Do not claim public-company disclosure equivalence"),
    ("poison/save", "intervention decision", "S047;S060;S063", "limited intervention resource and false-positive cost", "Potion effects are deterministic game rules", "Use as intervention option-value analogy", "Do not call it central-bank policy"),
    ("vote coordination", "coordinated market pressure", "S015;S030;S032", "coordinated actions can move collective outcome", "Votes directly determine elimination", "Use as group-action analogy", "Do not claim price-pressure dynamics"),
    ("payoff volatility", "strategic return variability", "S058;S062;S063", "variance around expected payoff", "Payoffs are game-defined utilities", "Use as a risk-return summary", "Do not call payoffs monetary returns"),
    ("Sharpe-like ratio", "risk-adjusted game payoff", "S058;S059", "mean reward per unit volatility/downside risk", "No risk-free rate or tradable asset exists", "Use only with like-for-like game payoffs", "Do not present as financial Sharpe ratio"),
    ("information premium", "payoff associated with useful private information", "S035;S036", "private information can improve returns", "Project premium can be outcome-dependent", "Use as descriptive game-payoff association", "Do not call it causal without randomized design"),
    ("manipulation premium", "payoff associated with successful manipulation", "S030;S022;S024", "manipulation can exploit others' beliefs", "Sample imbalance and role mechanics matter", "Use as bounded descriptive analogue", "Do not claim market manipulation premium is measured"),
]


CONTRADICTIONS = [
    ("R7-X01", "Position folklore was not supported after randomization.", "Common heuristic expected edge seats or edge-first checking to matter.", "S055;S057", "Randomized roles remove seat-role confounding.", "Folklore lacked randomized assignment.", "No human table dynamics.", "Seat probability and village win rate metrics.", "no", "A design artifact rather than a real contradiction."),
    ("R7-X02", "BoW failed under unseen templates.", "Text classifiers can perform well with sparse lexical features.", "S038;S040;S042", "Template shift changed lexical support.", "Classification benchmark differs from live policy.", "Generated templates rather than human speech.", "OOD AUC and live win rate.", "partly", "BoW success is domain-bound, not globally invalid."),
    ("R7-X03", "Highest p_wolf Seer checking was harmful.", "Behavioral-risk scores should identify wolves.", "S009;S042;S055", "p_wolf is post-treatment and can be manipulated or noisy.", "No equilibrium-solved belief model.", "Simulated agents, not human Bayesian actors.", "Live village win rate.", "yes but limited", "The project qualifies belief-score use."),
    ("R7-X04", "Shadow ML did not generalize live.", "Offline policy methods can estimate policy value.", "S046;S047;S048", "Support, compounding, and distribution-shift conditions were weak.", "Project did not use full OPE estimators.", "Complete-game dynamics.", "Live matched outcomes.", "no", "Consistent with OPE caution rather than contradiction."),
    ("R7-X05", "Aggressive Witch policy was promising despite wrong-poison risk.", "Risk controls often penalize aggressive action.", "S060;S063;S064", "Expected payoff can rise while tail risk also rises.", "Potion action is a discrete game resource.", "Role/team utility differs from investor utility.", "Mean payoff and waste metrics.", "no", "Risk-return tradeoff rather than contradiction."),
    ("R7-X06", "Werewolves had highest mean and risk-adjusted payoff.", "High return often accompanies higher volatility.", "S029;S058;S062", "Current payoff design rewards informed minority strongly.", "No competitive market equilibrium.", "Game role asymmetry.", "Role payoff ratios.", "no", "A model-specific efficient-frontier result."),
    ("R7-X07", "Immediate Seer reveal remains uncertain.", "Information disclosure can be valuable.", "S011;S035;S036", "Reveal also raises mortality hazard.", "Game contains explicit night kill targeting.", "No market-maker mechanism.", "Actor payoff and post-reveal hazard.", "no", "Disclosure has both public-good and exposure costs."),
    ("R7-X08", "Deep cover was harmful.", "Concealment can aid deceivers.", "S002;S003;S030", "Excess concealment reduced active pressure.", "Policy preset may not represent all deep-cover strategies.", "Simplified speech/deception environment.", "Live wolf win and payoff.", "partly", "Concealment needs strategic pressure to be useful."),
]


CLAIMS = [
    ("R7-C01", "Every major project chapter has at least one literature mapping.", "results/literature_synthesis_stage_r7/r7_finding_literature_comparison_matrix.csv", "S001;S055", "methodological claim", "fully_supported", "low", "No revision needed.", "Every major chapter is mapped to at least one cited source."),
    ("R7-C02", "Financial analogies are conceptual rather than causal market claims.", "results/literature_synthesis_stage_r7/r7_financial_analogy_crosswalk.csv", "S029;S030;S058;S063", "financial analogy", "fully_supported", "medium", "Keep qualification.", "The financial analogy is a bounded conceptual framework, not a causal claim about real markets."),
    ("R7-C03", "Low-information village weakness is consistent with hidden-role theory.", "experiment_report.md", "S001;S009", "theoretical interpretation", "fully_supported", "low", "No revision needed.", "Low-information village weakness is consistent with partial-information hidden-role theory."),
    ("R7-C04", "Trust-weighted voting is consistent with reputation-weighted aggregation.", "results/targeted_strategy_stage_r61/r61_villager_policy_summary.csv", "S019;S020;S021", "theoretical interpretation", "fully_supported", "low", "No revision needed.", "Trust-weighted voting parallels reputation-weighted aggregation."),
    ("R7-C05", "Herding can amplify error.", "trust_weighted_herding_experiment.py outputs", "S015;S016;S017", "literature-derived claim", "fully_supported", "low", "No revision needed.", "Herding can amplify public errors when social signals overwhelm private evidence."),
    ("R7-C06", "False accusation benefit is not causal market evidence.", "stage3_experiment_report.md", "S022;S024;S030", "causal claim", "requires_qualification", "high", "Use descriptive wording.", "False accusation showed game-specific descriptive effects under simulated rules."),
    ("R7-C07", "BoW template failure should be preserved.", "results/bow_speech_stage_r2/bow_template_generalization_metrics.csv", "S041;S042;S043", "project empirical result", "fully_supported", "low", "No revision needed.", "BoW template failure is a central negative result and should not be hidden."),
    ("R7-C08", "Live-policy failure outranks predictive performance.", "results/ml_optimization_stage2a/; results/ml_optimization_stage2b/", "S046;S047;S048;S050", "methodological claim", "fully_supported", "low", "No revision needed.", "Matched live complete-game outcomes should outrank shadow predictive metrics for policy claims."),
    ("R7-C09", "Immediate Seer reveal is promising but uncertain.", "results/targeted_strategy_stage_r61/r61_seer_research_report.md", "S011;S035;S036", "project empirical result", "fully_supported", "medium", "Keep uncertainty.", "Immediate reveal is promising but uncertain because exposure costs remain material."),
    ("R7-C10", "Witch aggressive_full is not globally optimal.", "results/targeted_strategy_stage_r61/r61_witch_research_report.md", "S057;S060;S064", "project empirical result", "fully_supported", "medium", "Keep pilot scope.", "Aggressive_full is the best tested pilot policy, not a globally optimal Witch policy."),
    ("R7-C11", "Hunter reference conclusion is preserved.", "results/targeted_strategy_stage_r61/r61_hunter_research_report.md", "S060;S063", "project empirical result", "fully_supported", "low", "No revision needed.", "Hunter reference remains the strongest tested policy under current evidence."),
    ("R7-C12", "Random wolf kill and deep-cover harm are preserved.", "results/targeted_strategy_stage_r61/r61_wolf_research_report.md", "S002;S006;S030", "project empirical result", "fully_supported", "low", "No revision needed.", "Random kill and deep-cover policy harm should remain in final evidence tables."),
    ("R7-C13", "No global optimality is claimed.", "results/role_strategy_synthesis_stage_r6/r6_research_report.md", "S055;S057", "methodological claim", "fully_supported", "low", "No revision needed.", "R7 does not claim global optimality for any strategy."),
    ("R7-C14", "Mesa is not used in this implementation.", "repository file inventory", "S053;S055;S056", "methodological claim", "project_only", "low", "State as implementation scope.", "The simulator is custom Python rather than Mesa-based."),
]


R8_READINESS = [
    ("every_major_chapter_has_literature_coverage", "pass", "All 41 required findings map to at least one source."),
    ("key_claims_have_citation_ready_sources", "pass", "Claim-support audit contains source-backed safe wording."),
    ("citation_metadata_validated", "pass_with_manual_review_items", "Manual-review items are explicit and non-blocking."),
    ("literature_and_project_evidence_separated", "pass", "Comparison matrix has separate project and literature fields."),
    ("financial_analogy_limitations_explicit", "pass", "Every crosswalk row has important_difference and overclaim_to_avoid."),
    ("contradictions_documented", "pass", "Contradiction registry records eight qualifying disagreements."),
    ("no_fake_citations_remain", "pass", "Tests reject fabricated/unflagged sources."),
    ("final_bibliography_usable", "pass_with_manual_review_items", "BibTeX and APA files are generated; book edition items need final manual review."),
    ("cumulative_reports_updated", "pass", "Research progress files updated with R7 rows and sections."),
    ("remaining_gaps_nonblocking_or_listed", "pass", "Limitations and manual-review files list unresolved metadata and scope limits."),
    ("r8_readiness_decision", "ready", "Proceed to R8 - Final Integrated Data Analysis and Evidence Tables."),
]
