"""R8 final research-question and hypothesis registries."""

from __future__ import annotations

from r8_common import ci_text, get_row, read_csv


RESEARCH_QUESTION_COLUMNS = [
    "research_question_id",
    "original_or_extended",
    "proposal_text",
    "operational_definition",
    "main_hypotheses",
    "completed_stages",
    "final_status",
    "primary_evidence",
    "main_result",
    "limitations",
    "final_report_section",
]

HYPOTHESIS_COLUMNS = [
    "hypothesis_id",
    "research_question_id",
    "stage_id",
    "role_or_mechanism",
    "hypothesis",
    "null_hypothesis",
    "primary_outcome",
    "independent_unit",
    "sample_size",
    "comparison",
    "effect_direction",
    "effect_size",
    "confidence_interval",
    "raw_p_value",
    "adjusted_p_value",
    "multiplicity_family",
    "seed_robustness",
    "regime_robustness",
    "leakage_status",
    "overfitting_status",
    "evidence_grade",
    "conclusion_status",
    "final_safe_wording",
    "literature_relationship",
    "project_source",
    "literature_source_ids",
]


def build_research_question_registry() -> list[dict[str, str]]:
    return [
        {
            "research_question_id": "RQ1",
            "original_or_extended": "original",
            "proposal_text": "How can qualitative speech be quantified using BoW features?",
            "operational_definition": "Generate tokenized speech utterances, compute BoW scores, validate predictive value, and test guarded live integration.",
            "main_hypotheses": "BoW features can quantify speech; predictive value should not be assumed to imply live policy value.",
            "completed_stages": "R2;R3;R7.1",
            "final_status": "completed_with_limitations",
            "primary_evidence": "results/bow_speech_stage_r2/bow_role_prediction_metrics.csv; results/bow_integration_stage_r3/r3_primary_game_contrasts.csv",
            "main_result": "BoW quantified speech and achieved moderate prediction, but OOD and live-policy failures prevent deployment as a primary decision policy.",
            "limitations": "Template-generated speech and no human dialogue corpus.",
            "final_report_section": "Speech and BoW findings",
        },
        {
            "research_question_id": "RQ2",
            "original_or_extended": "original",
            "proposal_text": "What payoff-maximizing strategies are supported for each role within the tested strategy space?",
            "operational_definition": "Use R5.1/R6/R6.1 actor-specific matched contrasts and R6.2 metric audits to recommend tested policies.",
            "main_hypotheses": "Role-specific policies differ in faction win rate, actor payoff, and risk exposure.",
            "completed_stages": "R5.1;R6;R6.1;R6.2",
            "final_status": "completed_with_limitations",
            "primary_evidence": "results/targeted_strategy_stage_r61/r61_global_primary_contrasts.csv",
            "main_result": "Villager trust-weighted voting is strongly supported; several harmful policies are rejected; some Seer and Witch candidates remain uncertain.",
            "limitations": "Strongest tested policies are not global optima.",
            "final_report_section": "Role-specific strategy findings",
        },
        {
            "research_question_id": "RQ3",
            "original_or_extended": "original",
            "proposal_text": "How can Werewolf decisions be interpreted using payoff, risk, opportunity cost, and financial-market analogy?",
            "operational_definition": "Apply the frozen R4 payoff ledger and R5 risk metrics to role and strategy outcomes.",
            "main_hypotheses": "Expected payoff and downside-risk metrics reveal different role and strategy tradeoffs.",
            "completed_stages": "R4;R5;R5.1;R7.1",
            "final_status": "completed_with_limitations",
            "primary_evidence": "results/financial_risk_stage_r5/r5_role_expected_payoff_summary.csv",
            "main_result": "Werewolf has the highest mean and risk-adjusted payoff; Hunter has the worst tail risk; financial analogy is bounded.",
            "limitations": "Game payoff analogues are not real financial returns.",
            "final_report_section": "Unified payoff and financial analogy",
        },
        {
            "research_question_id": "RQ4",
            "original_or_extended": "extended",
            "proposal_text": "Do predictive models improve live policy outcomes?",
            "operational_definition": "Compare predictive/shadow ML and BoW results against matched live complete-game policy deployment.",
            "main_hypotheses": "Predictive or shadow value may fail under live feedback and distribution shift.",
            "completed_stages": "ML Stage 1;ML Stage 1.5;ML Stage 2A;ML Stage 2B;R3",
            "final_status": "completed_with_negative_findings",
            "primary_evidence": "results/ml_optimization_stage2a/wolf_kill_primary_contrasts.csv; results/ml_optimization_stage2b/stage2b_primary_contrasts.csv",
            "main_result": "Predictive accuracy and shadow value did not justify live deployment; ML remains diagnostic only.",
            "limitations": "Evaluated frozen standard-library models, not the full space of ML policies.",
            "final_report_section": "Machine-learning findings",
        },
        {
            "research_question_id": "RQ5",
            "original_or_extended": "extended",
            "proposal_text": "How robust are conclusions to seed, regime, seat order, direction, and information leakage?",
            "operational_definition": "Use multi-seed, regime, randomized-role, label-neutral, mirror replay, leakage, and overfitting audits.",
            "main_hypotheses": "Apparent position or model effects may disappear under stricter validation.",
            "completed_stages": "randomized role; structured search; seat-order neutral; physical replay; R6.1;R6.2;R7.1",
            "final_status": "completed",
            "primary_evidence": "results/seat_order_neutral; results/physical_direction_replay; results/research_progress/documentation_validation_summary.csv",
            "main_result": "Engine symmetry and DOI/documentation validation passed; positional folklore was unsupported after randomization.",
            "limitations": "Simulation remains self-built and synthetic.",
            "final_report_section": "Validity and robustness",
        },
        {
            "research_question_id": "RQ6",
            "original_or_extended": "extended",
            "proposal_text": "Which early findings survive stricter grouped, matched, and live-policy validation?",
            "operational_definition": "Apply evidence priority to supersede pilot, shadow, proxy, and global-label claims where later evidence is stronger.",
            "main_hypotheses": "Some early descriptive gains will not survive grouped or matched live validation.",
            "completed_stages": "R3;ML Stage 1.5;ML Stage 2A;ML Stage 2B;R5.1;R6.2;R8",
            "final_status": "completed",
            "primary_evidence": "results/final_integrated_analysis_stage_r8/r8_superseded_result_registry.csv",
            "main_result": "Pilot ML and BoW predictive claims are qualified by live failures; R5 global labels are superseded by actor-specific attribution.",
            "limitations": "Some historical datasets lack event-level reconstruction.",
            "final_report_section": "Superseded findings",
        },
    ]


def build_final_hypothesis_registry() -> list[dict[str, str]]:
    r61 = read_csv("results/targeted_strategy_stage_r61/r61_global_primary_contrasts.csv")
    r3 = read_csv("results/bow_integration_stage_r3/r3_primary_game_contrasts.csv")
    ml2a = read_csv("results/ml_optimization_stage2a/wolf_kill_primary_contrasts.csv")
    ml2b = read_csv("results/ml_optimization_stage2b/stage2b_primary_contrasts.csv")

    villager_tw = get_row(r61, module="villager", candidate_policy="trust_weighted")
    hunter_no_shot = get_row(r61, module="hunter", candidate_policy="no_shot")
    witch_aggressive = get_row(r61, module="witch", candidate_policy="aggressive_full")
    witch_conservative = get_row(r61, module="witch", candidate_policy="conservative_full")
    wolf_deep = get_row(r61, module="wolf", candidate_policy="deep_cover")
    seer_immediate = get_row(r61, module="seer", candidate_policy="immediate_reveal")
    bow_guarded = get_row(r3, condition_name="guarded_bow_010_live")
    bow_structured = get_row(r3, condition_name="structured_bow_guarded_live")
    ml_hybrid = get_row(ml2a, policy_name="frozen_hybrid_50_50")
    ml_continuous = get_row(ml2b, policy_name="continuous_frozen_ml")

    return [
        {
            "hypothesis_id": "H_R8_01",
            "research_question_id": "RQ1",
            "stage_id": "R2",
            "role_or_mechanism": "BoW speech quantification",
            "hypothesis": "BoW features quantify speech signals with predictive value.",
            "null_hypothesis": "BoW features provide no useful role-prediction signal.",
            "primary_outcome": "final-test ROC-AUC",
            "independent_unit": "utterance with grouped split caveat",
            "sample_size": "8190 final-test utterance rows",
            "comparison": "BoW score models and structured-label models",
            "effect_direction": "positive predictive value",
            "effect_size": "bow_scores_only AUC 0.6918; full_bow_vector AUC 0.7576",
            "confidence_interval": "not_reported",
            "raw_p_value": "not_reported",
            "adjusted_p_value": "not_reported",
            "multiplicity_family": "not_applicable",
            "seed_robustness": "template split diagnostics reported",
            "regime_robustness": "regime generalization reported",
            "leakage_status": "audit_passed",
            "overfitting_status": "template_bound",
            "evidence_grade": "B",
            "conclusion_status": "promising_but_uncertain",
            "final_safe_wording": "BoW features quantify generated speech but should not be treated as a deployed decision policy.",
            "literature_relationship": "consistent with text-classification and domain-shift literature",
            "project_source": "results/bow_speech_stage_r2/bow_role_prediction_metrics.csv",
            "literature_source_ids": "S065;S068;S077",
        },
        {
            "hypothesis_id": "H_R8_02",
            "research_question_id": "RQ1",
            "stage_id": "R3",
            "role_or_mechanism": "BoW live voting",
            "hypothesis": "Guarded BoW integration improves live village outcomes.",
            "null_hypothesis": "Guarded BoW integration does not improve live village outcomes.",
            "primary_outcome": "village win rate",
            "independent_unit": "matched complete game set",
            "sample_size": bow_guarded["matched_sets"],
            "comparison": bow_guarded["comparison"],
            "effect_direction": "harmful",
            "effect_size": f"{bow_guarded['absolute_pp_difference']} pp",
            "confidence_interval": f"OR [{bow_guarded['odds_ratio_ci_low']}, {bow_guarded['odds_ratio_ci_high']}]",
            "raw_p_value": bow_guarded["raw_p_value"],
            "adjusted_p_value": bow_guarded["holm_adjusted_p_value"],
            "multiplicity_family": bow_guarded["multiplicity_method"],
            "seed_robustness": "reported in R3 seed robustness",
            "regime_robustness": "reported in R3 regime robustness",
            "leakage_status": "audit_passed",
            "overfitting_status": "template_bound_live_failure",
            "evidence_grade": "A-",
            "conclusion_status": "statistically_supported_harm",
            "final_safe_wording": "Live guarded BoW was harmful under tested integration rules.",
            "literature_relationship": "consistent with domain shift and offline policy failure literature",
            "project_source": "results/bow_integration_stage_r3/r3_primary_game_contrasts.csv",
            "literature_source_ids": "S065;S069;S070",
        },
        {
            "hypothesis_id": "H_R8_03",
            "research_question_id": "RQ1",
            "stage_id": "R3",
            "role_or_mechanism": "structured plus BoW live voting",
            "hypothesis": "Structured plus BoW guarded policy improves village outcomes.",
            "null_hypothesis": "Structured plus BoW guarded policy does not improve village outcomes.",
            "primary_outcome": "village win rate",
            "independent_unit": "matched complete game set",
            "sample_size": bow_structured["matched_sets"],
            "comparison": bow_structured["comparison"],
            "effect_direction": "harmful",
            "effect_size": f"{bow_structured['absolute_pp_difference']} pp",
            "confidence_interval": f"OR [{bow_structured['odds_ratio_ci_low']}, {bow_structured['odds_ratio_ci_high']}]",
            "raw_p_value": bow_structured["raw_p_value"],
            "adjusted_p_value": bow_structured["holm_adjusted_p_value"],
            "multiplicity_family": bow_structured["multiplicity_method"],
            "seed_robustness": "reported in R3 seed robustness",
            "regime_robustness": "reported in R3 regime robustness",
            "leakage_status": "audit_passed",
            "overfitting_status": "template_bound_live_failure",
            "evidence_grade": "A-",
            "conclusion_status": "statistically_supported_harm",
            "final_safe_wording": "Adding BoW to structured live voting should not be used as a final policy.",
            "literature_relationship": "consistent with shortcut learning and offline policy failure literature",
            "project_source": "results/bow_integration_stage_r3/r3_primary_game_contrasts.csv",
            "literature_source_ids": "S065;S069",
        },
        {
            "hypothesis_id": "H_R8_04",
            "research_question_id": "RQ2",
            "stage_id": "R6.1",
            "role_or_mechanism": "Villager voting",
            "hypothesis": "Trust-weighted Villager voting improves actor payoff relative to reference.",
            "null_hypothesis": "Trust-weighted Villager voting does not improve actor payoff.",
            "primary_outcome": "actor payoff",
            "independent_unit": "matched role-module set",
            "sample_size": villager_tw["matched_set_count"],
            "comparison": "trust_weighted vs reference",
            "effect_direction": "improvement",
            "effect_size": villager_tw["mean_difference"],
            "confidence_interval": ci_text(villager_tw["ci_low"], villager_tw["ci_high"]),
            "raw_p_value": villager_tw["raw_p_value"],
            "adjusted_p_value": villager_tw["holm_adjusted_p_value"],
            "multiplicity_family": "villager role-policy family",
            "seed_robustness": "reported",
            "regime_robustness": "reported",
            "leakage_status": "audit_passed",
            "overfitting_status": "not_applicable",
            "evidence_grade": "A",
            "conclusion_status": "statistically_supported_improvement",
            "final_safe_wording": "Trust-weighted voting is the strongest tested Villager policy, not a global optimum.",
            "literature_relationship": "consistent with reputation-weighted aggregation literature",
            "project_source": "results/targeted_strategy_stage_r61/r61_villager_primary_contrasts.csv",
            "literature_source_ids": "S025;S079;S083",
        },
        {
            "hypothesis_id": "H_R8_05",
            "research_question_id": "RQ2",
            "stage_id": "R6.1",
            "role_or_mechanism": "Hunter policy",
            "hypothesis": "Hunter no-shot policy is competitive with reference.",
            "null_hypothesis": "Hunter no-shot does not differ from reference.",
            "primary_outcome": "actor payoff",
            "independent_unit": "matched role-module set",
            "sample_size": hunter_no_shot["matched_set_count"],
            "comparison": "no_shot vs reference",
            "effect_direction": "harmful",
            "effect_size": hunter_no_shot["mean_difference"],
            "confidence_interval": ci_text(hunter_no_shot["ci_low"], hunter_no_shot["ci_high"]),
            "raw_p_value": hunter_no_shot["raw_p_value"],
            "adjusted_p_value": hunter_no_shot["holm_adjusted_p_value"],
            "multiplicity_family": "hunter role-policy family",
            "seed_robustness": "reported",
            "regime_robustness": "reported",
            "leakage_status": "audit_passed",
            "overfitting_status": "not_applicable",
            "evidence_grade": "A",
            "conclusion_status": "statistically_supported_harm",
            "final_safe_wording": "Hunter no-shot is rejected under tested conditions.",
            "literature_relationship": "consistent with downside-risk literature",
            "project_source": "results/targeted_strategy_stage_r61/r61_hunter_primary_contrasts.csv",
            "literature_source_ids": "S074;S087;S088",
        },
        {
            "hypothesis_id": "H_R8_06",
            "research_question_id": "RQ2",
            "stage_id": "R6.1",
            "role_or_mechanism": "Seer reveal",
            "hypothesis": "Immediate reveal improves Seer actor payoff.",
            "null_hypothesis": "Immediate reveal does not improve Seer actor payoff.",
            "primary_outcome": "actor payoff and exposure",
            "independent_unit": "matched role-module set",
            "sample_size": seer_immediate["matched_set_count"],
            "comparison": "immediate_reveal vs private_only",
            "effect_direction": "positive payoff with exposure tradeoff",
            "effect_size": seer_immediate["mean_difference"],
            "confidence_interval": ci_text(seer_immediate["ci_low"], seer_immediate["ci_high"]),
            "raw_p_value": seer_immediate["raw_p_value"],
            "adjusted_p_value": seer_immediate["holm_adjusted_p_value"],
            "multiplicity_family": "seer role-policy family",
            "seed_robustness": "reported",
            "regime_robustness": "reported",
            "leakage_status": "audit_passed",
            "overfitting_status": "not_applicable",
            "evidence_grade": "B",
            "conclusion_status": "promising_but_uncertain",
            "final_safe_wording": "Immediate reveal is promising but remains exposure-sensitive.",
            "literature_relationship": "consistent with information disclosure and persuasion literature",
            "project_source": "results/targeted_strategy_stage_r61/r61_seer_primary_contrasts.csv; results/metrics_integrity_stage_r62/r62_seer_post_reveal_hazard_summary.csv",
            "literature_source_ids": "S071;S081;S082",
        },
        {
            "hypothesis_id": "H_R8_07",
            "research_question_id": "RQ2",
            "stage_id": "R6.1/R6.2",
            "role_or_mechanism": "Witch joint policy",
            "hypothesis": "Aggressive full Witch policy improves payoff without unacceptable waste.",
            "null_hypothesis": "Aggressive full Witch policy is not better than reference.",
            "primary_outcome": "actor payoff and potion waste",
            "independent_unit": "matched role-module set plus lifecycle audit",
            "sample_size": witch_aggressive["matched_set_count"],
            "comparison": "aggressive_full vs reference",
            "effect_direction": "positive payoff with waste tradeoff",
            "effect_size": witch_aggressive["mean_difference"],
            "confidence_interval": ci_text(witch_aggressive["ci_low"], witch_aggressive["ci_high"]),
            "raw_p_value": witch_aggressive["raw_p_value"],
            "adjusted_p_value": witch_aggressive["holm_adjusted_p_value"],
            "multiplicity_family": "witch role-policy family",
            "seed_robustness": "reported",
            "regime_robustness": "reported",
            "leakage_status": "audit_passed",
            "overfitting_status": "not_applicable",
            "evidence_grade": "B",
            "conclusion_status": "promising_but_uncertain",
            "final_safe_wording": "Aggressive full Witch play remains experimental because R6.2 shows waste and opportunity-cost tradeoffs.",
            "literature_relationship": "consistent with intervention and risk-cost framing",
            "project_source": "results/targeted_strategy_stage_r61/r61_witch_primary_contrasts.csv; results/metrics_integrity_stage_r62/r62_witch_potion_waste_summary.csv",
            "literature_source_ids": "S070;S087",
        },
        {
            "hypothesis_id": "H_R8_08",
            "research_question_id": "RQ2",
            "stage_id": "R6.1",
            "role_or_mechanism": "Witch conservative policy",
            "hypothesis": "Conservative full Witch policy protects resources without harming payoff.",
            "null_hypothesis": "Conservative full Witch policy does not differ from reference.",
            "primary_outcome": "actor payoff",
            "independent_unit": "matched role-module set",
            "sample_size": witch_conservative["matched_set_count"],
            "comparison": "conservative_full vs reference",
            "effect_direction": "harmful",
            "effect_size": witch_conservative["mean_difference"],
            "confidence_interval": ci_text(witch_conservative["ci_low"], witch_conservative["ci_high"]),
            "raw_p_value": witch_conservative["raw_p_value"],
            "adjusted_p_value": witch_conservative["holm_adjusted_p_value"],
            "multiplicity_family": "witch role-policy family",
            "seed_robustness": "reported",
            "regime_robustness": "reported",
            "leakage_status": "audit_passed",
            "overfitting_status": "not_applicable",
            "evidence_grade": "A",
            "conclusion_status": "statistically_supported_harm",
            "final_safe_wording": "Conservative full Witch policy is rejected under tested conditions.",
            "literature_relationship": "consistent with opportunity-cost framing",
            "project_source": "results/targeted_strategy_stage_r61/r61_witch_primary_contrasts.csv",
            "literature_source_ids": "S070;S087;S088",
        },
        {
            "hypothesis_id": "H_R8_09",
            "research_question_id": "RQ2",
            "stage_id": "R6.1",
            "role_or_mechanism": "Werewolf deception/aggression",
            "hypothesis": "Deep-cover Werewolf policy improves wolf payoff.",
            "null_hypothesis": "Deep-cover policy does not differ from reference.",
            "primary_outcome": "actor payoff",
            "independent_unit": "matched role-module set",
            "sample_size": wolf_deep["matched_set_count"],
            "comparison": "deep_cover vs reference",
            "effect_direction": "harmful",
            "effect_size": wolf_deep["mean_difference"],
            "confidence_interval": ci_text(wolf_deep["ci_low"], wolf_deep["ci_high"]),
            "raw_p_value": wolf_deep["raw_p_value"],
            "adjusted_p_value": wolf_deep["holm_adjusted_p_value"],
            "multiplicity_family": "wolf role-policy family",
            "seed_robustness": "reported",
            "regime_robustness": "reported",
            "leakage_status": "audit_passed",
            "overfitting_status": "not_applicable",
            "evidence_grade": "A",
            "conclusion_status": "statistically_supported_harm",
            "final_safe_wording": "Deep-cover wolf strategy is rejected under tested conditions.",
            "literature_relationship": "consistent with credibility-cost and manipulation-risk framing",
            "project_source": "results/targeted_strategy_stage_r61/r61_wolf_primary_contrasts.csv",
            "literature_source_ids": "S002;S003;S076;S084",
        },
        {
            "hypothesis_id": "H_R8_10",
            "research_question_id": "RQ3",
            "stage_id": "R5",
            "role_or_mechanism": "risk-adjusted payoff",
            "hypothesis": "Expected payoff and risk-adjusted payoff distinguish role incentives.",
            "null_hypothesis": "Risk metrics add no interpretive value beyond win rate.",
            "primary_outcome": "mean payoff, downside deviation, Sharpe-like, Sortino-like, CVaR-like",
            "independent_unit": "game-level bootstrap with player rows clustered by game",
            "sample_size": "2000 validation games; 40000 player rows",
            "comparison": "roles under core payoff specification",
            "effect_direction": "differentiates roles",
            "effect_size": "Werewolf highest mean 1.2095 and highest Sharpe-like 0.8434; Hunter worst CVaR95-like 2.2675",
            "confidence_interval": "bootstrap CIs in r5_bootstrap_confidence_intervals.csv",
            "raw_p_value": "not_applicable",
            "adjusted_p_value": "not_applicable",
            "multiplicity_family": "not_applicable",
            "seed_robustness": "reported",
            "regime_robustness": "reported",
            "leakage_status": "audit_passed",
            "overfitting_status": "not_applicable",
            "evidence_grade": "A",
            "conclusion_status": "statistically_supported_improvement",
            "final_safe_wording": "Financial-risk metrics are valid as game-payoff analogues, not real financial returns.",
            "literature_relationship": "consistent with risk-measure literature",
            "project_source": "results/financial_risk_stage_r5/r5_role_expected_payoff_summary.csv",
            "literature_source_ids": "S058;S059;S060;S074;S087;S088",
        },
        {
            "hypothesis_id": "H_R8_11",
            "research_question_id": "RQ4",
            "stage_id": "ML2A",
            "role_or_mechanism": "ML wolf-kill policy",
            "hypothesis": "Frozen ML or hybrid wolf-kill policies improve live wolf win rate.",
            "null_hypothesis": "Frozen ML policies do not improve live wolf win rate.",
            "primary_outcome": "wolf win rate",
            "independent_unit": "matched live complete-game set",
            "sample_size": ml_hybrid["matched_sets"],
            "comparison": "frozen_hybrid_50_50 vs existing_rule",
            "effect_direction": "harmful",
            "effect_size": ml_hybrid["absolute_difference"],
            "confidence_interval": f"[{ml_hybrid['difference_ci_low']}, {ml_hybrid['difference_ci_high']}]",
            "raw_p_value": ml_hybrid["raw_p_value"],
            "adjusted_p_value": ml_hybrid["holm_adjusted_p_value"],
            "multiplicity_family": "ML Stage 2A live policy family",
            "seed_robustness": "reported",
            "regime_robustness": "reported",
            "leakage_status": "audit_passed",
            "overfitting_status": "shadow optimism failed live",
            "evidence_grade": "A-",
            "conclusion_status": "statistically_supported_harm",
            "final_safe_wording": "Frozen hybrid ML was harmful; ML should remain diagnostic.",
            "literature_relationship": "consistent with offline policy failure literature",
            "project_source": "results/ml_optimization_stage2a/wolf_kill_primary_contrasts.csv",
            "literature_source_ids": "S069;S070",
        },
        {
            "hypothesis_id": "H_R8_12",
            "research_question_id": "RQ4",
            "stage_id": "ML2B",
            "role_or_mechanism": "continuous ML control",
            "hypothesis": "Continuous frozen ML can recover wolf win rate after diagnostic tuning.",
            "null_hypothesis": "Continuous frozen ML does not improve wolf win rate.",
            "primary_outcome": "wolf win rate",
            "independent_unit": "matched live complete-game set",
            "sample_size": ml_continuous["matched_sets"],
            "comparison": "continuous_frozen_ml vs existing_rule",
            "effect_direction": "harmful_direction_not_Holm_significant",
            "effect_size": ml_continuous["absolute_difference"],
            "confidence_interval": f"[{ml_continuous['difference_ci_low']}, {ml_continuous['difference_ci_high']}]",
            "raw_p_value": ml_continuous["raw_p_value"],
            "adjusted_p_value": ml_continuous["holm_adjusted_p_value"],
            "multiplicity_family": "ML Stage 2B diagnostic policy family",
            "seed_robustness": "reported",
            "regime_robustness": "reported",
            "leakage_status": "audit_passed",
            "overfitting_status": "distribution_shift_and_compounding_concern",
            "evidence_grade": "B",
            "conclusion_status": "promising_but_uncertain",
            "final_safe_wording": "Continuous frozen ML is not recommended; evidence is diagnostic rather than deployable.",
            "literature_relationship": "consistent with offline policy and shortcut-learning literature",
            "project_source": "results/ml_optimization_stage2b/stage2b_primary_contrasts.csv",
            "literature_source_ids": "S065;S069;S070",
        },
        {
            "hypothesis_id": "H_R8_13",
            "research_question_id": "RQ5",
            "stage_id": "seat_position_randomized_roles",
            "role_or_mechanism": "seat-position folklore",
            "hypothesis": "Edge-priority checking retains an advantage after role randomization.",
            "null_hypothesis": "Edge-priority checking has no robust advantage after role randomization.",
            "primary_outcome": "village win rate and first-check wolf rate",
            "independent_unit": "complete game",
            "sample_size": "17500 games",
            "comparison": "edge_first vs random and role randomized seat balance",
            "effect_direction": "unsupported",
            "effect_size": "edge_first first-check wolf 34.20% vs random 34.72%; adjusted village model OR 1.05",
            "confidence_interval": "OR CI 0.94 to 1.17",
            "raw_p_value": "0.417",
            "adjusted_p_value": "not_significant_after_correction",
            "multiplicity_family": "seat-position strategy family",
            "seed_robustness": "reported",
            "regime_robustness": "not_reported",
            "leakage_status": "not_applicable",
            "overfitting_status": "not_applicable",
            "evidence_grade": "A-",
            "conclusion_status": "no_supported_improvement",
            "final_safe_wording": "Edge-position folklore is unsupported after randomized role assignment.",
            "literature_relationship": "consistent with simulation-validation caution literature",
            "project_source": "results/data_analysis/seer_position_game_level/analysis_report.md",
            "literature_source_ids": "S066;S067",
        },
        {
            "hypothesis_id": "H_R8_14",
            "research_question_id": "RQ5",
            "stage_id": "physical_direction_replay",
            "role_or_mechanism": "engine symmetry",
            "hypothesis": "Supplied-action and mirror replay preserve outcomes if the engine is symmetric.",
            "null_hypothesis": "Replay or mirror transformation changes outcomes.",
            "primary_outcome": "match rate and divergence count",
            "independent_unit": "replay pair",
            "sample_size": "8500 validation pairs",
            "comparison": "source versus exact/mirror replay",
            "effect_direction": "validation_passed",
            "effect_size": "100% match rate; 0 divergences",
            "confidence_interval": "not_applicable",
            "raw_p_value": "not_applicable",
            "adjusted_p_value": "not_applicable",
            "multiplicity_family": "not_applicable",
            "seed_robustness": "not_applicable",
            "regime_robustness": "not_applicable",
            "leakage_status": "not_applicable",
            "overfitting_status": "not_applicable",
            "evidence_grade": "A",
            "conclusion_status": "diagnostic_only",
            "final_safe_wording": "Replay and mirror validation support engine symmetry, not strategy superiority.",
            "literature_relationship": "consistent with replication and ABM validation literature",
            "project_source": "results/physical_direction_replay/physical_direction_replay_experiment_report.md",
            "literature_source_ids": "S066;S067",
        },
    ]
