"""R8 sample-unit registry."""

SAMPLE_UNIT_COLUMNS = [
    "unit_type",
    "definition",
    "stages_using_unit",
    "total_rows",
    "independent_or_clustered",
    "clustering_variable",
    "valid_for_inference",
    "valid_for_descriptive_analysis",
    "can_be_summed_across_stages",
    "overlap_risk",
    "final_reporting_rule",
    "notes",
]


def build_sample_unit_registry() -> list[dict[str, str]]:
    return [
        {
            "unit_type": "independent_complete_game",
            "definition": "A fully executed live game under one policy/condition.",
            "stages_using_unit": "R3, seer position, structured search, seat-order, ML 2A/2B, R6.1",
            "total_rows": "stage_specific",
            "independent_or_clustered": "clustered when matched or seeded",
            "clustering_variable": "matched_set_id, seed, behavioral_regime, or game_family_id",
            "valid_for_inference": "yes when model accounts for matching/clustering",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "same configurations can appear in copied or derived datasets",
            "final_reporting_rule": "Report stage-level game counts and independent unit; do not claim a single project-wide independent N.",
            "notes": "Complete games are the highest empirical unit for live outcome claims.",
        },
        {
            "unit_type": "matched_configuration_set",
            "definition": "A shared base state or seed/configuration used to compare policies.",
            "stages_using_unit": "R3, ML 2A, ML 2B, R6.1, seat-order-neutral",
            "total_rows": "stage_specific",
            "independent_or_clustered": "matched",
            "clustering_variable": "matched_set_id or pair_id",
            "valid_for_inference": "yes for paired contrasts",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "matched identifiers are local to a stage",
            "final_reporting_rule": "Matched policy games are not independent observations; analyze policy differences within matched sets.",
            "notes": "This is the preferred unit for policy-vs-reference contrasts.",
        },
        {
            "unit_type": "seed",
            "definition": "Random seed used to generate repeated conditions.",
            "stages_using_unit": "multi-seed robustness, R6.1, ML, structured search",
            "total_rows": "at least 20 distinct final R6.1 seeds",
            "independent_or_clustered": "cluster label",
            "clustering_variable": "seed",
            "valid_for_inference": "diagnostic unless explicitly modeled",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "same numeric seed can recur in unrelated generators",
            "final_reporting_rule": "Use seed-level robustness within each experiment.",
            "notes": "A seed is not itself a game outcome.",
        },
        {
            "unit_type": "behavioral_regime",
            "definition": "Configuration family controlling mechanism settings.",
            "stages_using_unit": "R5, R5.1, R6.1, ML stages, BoW integration",
            "total_rows": "stage_specific",
            "independent_or_clustered": "cluster or stratification variable",
            "clustering_variable": "behavioral_regime",
            "valid_for_inference": "yes for robustness/heterogeneity checks",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "regime names and definitions differ across early stages",
            "final_reporting_rule": "Use as robustness strata, not independent sample size.",
            "notes": "R6.1 uses 10 behavioral regimes.",
        },
        {
            "unit_type": "player_game_row",
            "definition": "One player or role's payoff/outcome row within one game.",
            "stages_using_unit": "R4, R5, R5.1",
            "total_rows": "40000 R4 rows; 40000 R5 rows over shared validation games",
            "independent_or_clustered": "clustered within game",
            "clustering_variable": "game_id",
            "valid_for_inference": "yes only with game-level bootstrap or clustered design",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "R4 and R5 derive from same validation games",
            "final_reporting_rule": "Player rows from the same game are clustered.",
            "notes": "Use R5 for final risk metrics and R4 for payoff ledger validation.",
        },
        {
            "unit_type": "action_event",
            "definition": "A logged role action, vote, speech, death, or payoff event.",
            "stages_using_unit": "R3, R4, R6.1, R6.2",
            "total_rows": "stage_specific",
            "independent_or_clustered": "nested within games",
            "clustering_variable": "game_id",
            "valid_for_inference": "diagnostic only unless aggregated to game/matched set",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "events differ by logger and policy condition",
            "final_reporting_rule": "Event rows are not independent games.",
            "notes": "Useful for mechanism and lifecycle audits.",
        },
        {
            "unit_type": "speech_utterance",
            "definition": "One generated speech string or speech event.",
            "stages_using_unit": "R2 and R3",
            "total_rows": "32721 R2 utterances; 228471 R3 live speech events",
            "independent_or_clustered": "nested within game, speaker, template, and condition",
            "clustering_variable": "game_id/game_uid, template_family, speaker",
            "valid_for_inference": "predictive validation only with grouped splits",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "template families and generated speech are repeated structures",
            "final_reporting_rule": "Utterances are not independent game outcomes.",
            "notes": "BoW feature claims must remain separate from live policy claims.",
        },
        {
            "unit_type": "vote_event",
            "definition": "One vote decision or vote-quality record.",
            "stages_using_unit": "R3 and R6.1 Villager",
            "total_rows": "318558 vote rows across R3 and R6.1 before overlap adjustment",
            "independent_or_clustered": "nested within games and policies",
            "clustering_variable": "game_id, matched_set_id, policy",
            "valid_for_inference": "only after aggregation or matched design",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "multiple votes per game and multiple policies per matched set",
            "final_reporting_rule": "Vote rows are mechanism diagnostics, not independent games.",
            "notes": "Use role-policy matched summaries for final Villager strategy claims.",
        },
        {
            "unit_type": "belief_update",
            "definition": "One suspicion or p_wolf update row.",
            "stages_using_unit": "R3",
            "total_rows": "194810",
            "independent_or_clustered": "nested within game and target",
            "clustering_variable": "game_uid, belief_target",
            "valid_for_inference": "diagnostic only",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "belief updates share game context and speakers",
            "final_reporting_rule": "Use for mechanism diagnosis, not final win-rate inference.",
            "notes": "Belief effects support explanation of BoW live failure.",
        },
        {
            "unit_type": "rollout_branch",
            "definition": "A simulated continuation or counterfactual branch from a decision state.",
            "stages_using_unit": "ML 1.5, ML 2B, BoW R3",
            "total_rows": "16932 confirmed rollout/counterfactual rows",
            "independent_or_clustered": "nested within source decision state",
            "clustering_variable": "decision_id or source game",
            "valid_for_inference": "diagnostic/counterfactual only",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "branches share source state and random continuation assumptions",
            "final_reporting_rule": "Rollout branches are not live games.",
            "notes": "Live complete-game evidence outranks rollout evidence.",
        },
        {
            "unit_type": "counterfactual_candidate_action",
            "definition": "A legal action candidate evaluated offline or in shadow mode.",
            "stages_using_unit": "ML and BoW diagnostics",
            "total_rows": "stage_specific",
            "independent_or_clustered": "nested within decision state",
            "clustering_variable": "decision_id",
            "valid_for_inference": "prediction/model diagnostics only",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "same decision contributes multiple candidate rows",
            "final_reporting_rule": "Candidate rows are not independent games.",
            "notes": "Do not turn candidate-row AUC into policy efficacy.",
        },
        {
            "unit_type": "literature_source",
            "definition": "One retained source or DOI-backed replacement source.",
            "stages_using_unit": "R7 and R7.1",
            "total_rows": "64 R7 retained sources; 44 R7.1 final DOI-backed sources",
            "independent_or_clustered": "bibliography item",
            "clustering_variable": "not_applicable",
            "valid_for_inference": "not_applicable",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "yes_as_bibliography_inventory_only",
            "overlap_risk": "sources can support multiple findings",
            "final_reporting_rule": "Literature sources are not empirical samples.",
            "notes": "Final citations must come from R7.1 DOI-only bibliography.",
        },
        {
            "unit_type": "finding_literature_mapping",
            "definition": "One mapping between a project finding and a literature source.",
            "stages_using_unit": "R7.1 and R8",
            "total_rows": "98",
            "independent_or_clustered": "claim-support mapping",
            "clustering_variable": "project_finding_id",
            "valid_for_inference": "not_applicable",
            "valid_for_descriptive_analysis": "yes",
            "can_be_summed_across_stages": "no",
            "overlap_risk": "one source can map to multiple findings",
            "final_reporting_rule": "Literature mapping rows are not empirical samples.",
            "notes": "Use mappings to support final report citations and limitations.",
        },
    ]
