"""R8 experiment inventory and project scale synthesis."""

from __future__ import annotations

from r8_common import read_csv, row_count, unique_count


INVENTORY_COLUMNS = [
    "stage_id",
    "experiment_id",
    "research_question",
    "experiment_type",
    "role_or_mechanism",
    "policies_or_conditions",
    "raw_game_rows",
    "unique_games",
    "matched_sets",
    "seeds",
    "regimes",
    "player_rows",
    "event_rows",
    "utterance_rows",
    "rollout_rows",
    "candidate_rows",
    "independent_unit",
    "primary_outcome",
    "secondary_outcomes",
    "formal_inference",
    "multiplicity_method",
    "manifest_or_hash",
    "source_report",
    "source_data",
    "evidence_status",
    "included_in_final_analysis",
    "exclusion_reason",
    "notes",
]


def _count(path: str) -> str:
    try:
        return str(row_count(path))
    except FileNotFoundError:
        return "not_reported"


def _uniq(path: str, column: str) -> str:
    try:
        return str(unique_count(path, column))
    except FileNotFoundError:
        return "not_reported"


def _summary_games(path: str, game_column: str = "num_games") -> str:
    try:
        total = sum(int(float(row.get(game_column, "0") or 0)) for row in read_csv(path))
    except FileNotFoundError:
        return "not_reported"
    return str(total)


def build_experiment_inventory() -> list[dict[str, str]]:
    return [
        {
            "stage_id": "stage1_stage2_ablation",
            "experiment_id": "ablation_baseline_to_mechanisms",
            "research_question": "RQ2",
            "experiment_type": "single-seed descriptive ablation",
            "role_or_mechanism": "core roles, speech, seer, witch, hunter, deception, trust",
            "policies_or_conditions": "15 ablation rows",
            "raw_game_rows": "summary_only",
            "unique_games": "not_reported",
            "matched_sets": "not_applicable",
            "seeds": "1",
            "regimes": "not_reported",
            "player_rows": "not_reported",
            "event_rows": "not_reported",
            "utterance_rows": "not_reported",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "condition-level descriptive summary",
            "primary_outcome": "wolf/village win rate",
            "secondary_outcomes": "events, role-action counts",
            "formal_inference": "no",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "not_applicable",
            "source_report": "results/experiment_results.md",
            "source_data": "results/ablation_results.csv",
            "evidence_status": "descriptive_only",
            "included_in_final_analysis": "yes_qualified",
            "exclusion_reason": "not_applicable",
            "notes": "Early single-seed summary; later role-specific stages supersede strategy claims.",
        },
        {
            "stage_id": "stage4_speaker_memory",
            "experiment_id": "speaker_memory_sensitivity",
            "research_question": "RQ2",
            "experiment_type": "single-seed sensitivity",
            "role_or_mechanism": "speaker memory and trust-weighted voting",
            "policies_or_conditions": "trust_vote_weight sweep",
            "raw_game_rows": "summary_only",
            "unique_games": "3000 reported in sensitivity output",
            "matched_sets": "not_reported",
            "seeds": "1",
            "regimes": "not_reported",
            "player_rows": "not_reported",
            "event_rows": "not_reported",
            "utterance_rows": "not_reported",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "complete game summary",
            "primary_outcome": "village win rate",
            "secondary_outcomes": "trust updates",
            "formal_inference": "no",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "not_applicable",
            "source_report": "stage4_experiment_report.md",
            "source_data": "speaker_memory_sensitivity.py output summarized in stage4_experiment_report.md",
            "evidence_status": "descriptive_only",
            "included_in_final_analysis": "yes_qualified",
            "exclusion_reason": "not_applicable",
            "notes": "Superseded for role-specific strategy conclusions by R6/R6.1.",
        },
        {
            "stage_id": "ten_player_risk_preference",
            "experiment_id": "risk_preference_multi_seed",
            "research_question": "RQ5",
            "experiment_type": "multi-seed summary",
            "role_or_mechanism": "risk preference",
            "policies_or_conditions": "8 risk-preference conditions",
            "raw_game_rows": "summary_only",
            "unique_games": _summary_games("results/ten_player_risk_preference_multi_seed_raw.csv"),
            "matched_sets": "not_reported",
            "seeds": "5",
            "regimes": "not_reported",
            "player_rows": "not_reported",
            "event_rows": "not_reported",
            "utterance_rows": "not_reported",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "seed-condition summary of complete games",
            "primary_outcome": "wolf/village win rate",
            "secondary_outcomes": "risk-preference payoff by type",
            "formal_inference": "descriptive multi-seed",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "not_applicable",
            "source_report": "risk_preference_experiment_report.md",
            "source_data": "results/ten_player_risk_preference_multi_seed_raw.csv",
            "evidence_status": "promising_but_uncertain",
            "included_in_final_analysis": "yes_qualified",
            "exclusion_reason": "not_applicable",
            "notes": "Useful robustness context, not a final role-owned strategy test.",
        },
        {
            "stage_id": "seer_position_randomized_roles",
            "experiment_id": "randomized_role_seer_position",
            "research_question": "RQ5",
            "experiment_type": "multi-seed complete games",
            "role_or_mechanism": "seer position and seat-role randomization",
            "policies_or_conditions": "7 seer-check conditions",
            "raw_game_rows": _count("results/ten_player_seer_position_randomized_roles_game_level_raw.csv"),
            "unique_games": _uniq("results/ten_player_seer_position_randomized_roles_game_level_raw.csv", "game_id"),
            "matched_sets": "not_reported",
            "seeds": "5",
            "regimes": "not_reported",
            "player_rows": "not_reported",
            "event_rows": "not_reported",
            "utterance_rows": "not_reported",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "complete game",
            "primary_outcome": "village win rate",
            "secondary_outcomes": "first-check wolf rate, seer survival, seat role balance",
            "formal_inference": "yes",
            "multiplicity_method": "Holm where applicable",
            "manifest_or_hash": "not_applicable",
            "source_report": "seer_position_randomized_roles_report.md",
            "source_data": "results/ten_player_seer_position_randomized_roles_game_level_raw.csv",
            "evidence_status": "hypothesis_rejected_for_edge_folklore",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Randomized roles remove fixed seat-role confounds.",
        },
        {
            "stage_id": "structured_seer_search",
            "experiment_id": "structured_seer_search",
            "research_question": "RQ2;RQ5",
            "experiment_type": "multi-seed strategy comparison",
            "role_or_mechanism": "seer search strategy",
            "policies_or_conditions": "14 search strategies",
            "raw_game_rows": _count("results/structured_seer_search/structured_seer_search_game_level_raw.csv"),
            "unique_games": _uniq("results/structured_seer_search/structured_seer_search_game_level_raw.csv", "game_id"),
            "matched_sets": "not_applicable",
            "seeds": "5",
            "regimes": "not_reported",
            "player_rows": "not_reported",
            "event_rows": "not_reported",
            "utterance_rows": "not_reported",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "complete game",
            "primary_outcome": "village win rate",
            "secondary_outcomes": "wolf discovery and path diversity",
            "formal_inference": "yes",
            "multiplicity_method": "Holm",
            "manifest_or_hash": "not_applicable",
            "source_report": "results/data_analysis/structured_seer_search/analysis_report.md",
            "source_data": "results/structured_seer_search/structured_seer_search_game_level_raw.csv",
            "evidence_status": "mixed",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Diversified search was promising; behavioral exploitation strategies were harmful.",
        },
        {
            "stage_id": "seat_order_neutral",
            "experiment_id": "seat_label_and_direction_validation",
            "research_question": "RQ5",
            "experiment_type": "deterministic duplicate and paired validation",
            "role_or_mechanism": "engine label/direction artifacts",
            "policies_or_conditions": "normal, mirrored, rotated labels and directional strategies",
            "raw_game_rows": _count("results/seat_order_neutral/seat_order_neutral_game_level_raw.csv"),
            "unique_games": _uniq("results/seat_order_neutral/seat_order_neutral_game_level_raw.csv", "game_id"),
            "matched_sets": _uniq("results/seat_order_neutral/seat_order_neutral_game_level_raw.csv", "matched_set_id"),
            "seeds": "5",
            "regimes": "not_reported",
            "player_rows": "not_reported",
            "event_rows": "not_reported",
            "utterance_rows": "not_reported",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "matched physical configuration",
            "primary_outcome": "label-invariance divergence rate",
            "secondary_outcomes": "paired village win differences",
            "formal_inference": "yes after duplicate collapse",
            "multiplicity_method": "Holm",
            "manifest_or_hash": "not_applicable",
            "source_report": "results/data_analysis/seat_order_neutral/analysis_report.md",
            "source_data": "results/seat_order_neutral/seat_order_neutral_game_level_raw.csv",
            "evidence_status": "engine_symmetry_validated",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Displayed-label duplicates are not independent observations.",
        },
        {
            "stage_id": "physical_direction_replay",
            "experiment_id": "supplied_action_and_mirror_replay",
            "research_question": "RQ5",
            "experiment_type": "supplied-action replay validation",
            "role_or_mechanism": "physical direction symmetry",
            "policies_or_conditions": "exact replay, physical mirror, strategy mirror",
            "raw_game_rows": _count("results/physical_direction_replay/supplied_action_replay_game_level_raw.csv"),
            "unique_games": _uniq("results/physical_direction_replay/supplied_action_replay_game_level_raw.csv", "game_id"),
            "matched_sets": _uniq("results/physical_direction_replay/supplied_action_replay_game_level_raw.csv", "pair_id"),
            "seeds": "not_central",
            "regimes": "not_reported",
            "player_rows": "not_reported",
            "event_rows": "not_reported",
            "utterance_rows": "not_reported",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "replay pair",
            "primary_outcome": "replay match rate",
            "secondary_outcomes": "mirror divergence count",
            "formal_inference": "deterministic validation",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "not_applicable",
            "source_report": "results/physical_direction_replay/physical_direction_replay_experiment_report.md",
            "source_data": "results/physical_direction_replay/supplied_action_replay_summary.csv",
            "evidence_status": "engine_symmetry_validated",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Replay rows validate engine behavior, not strategic superiority.",
        },
        {
            "stage_id": "bow_stage_r2",
            "experiment_id": "formal_bow_speech_quantification",
            "research_question": "RQ1",
            "experiment_type": "predictive and descriptive speech analysis",
            "role_or_mechanism": "Bag-of-Words speech signals",
            "policies_or_conditions": "lexicon, scores, role prediction, template generalization",
            "raw_game_rows": "not_applicable",
            "unique_games": "not_reported",
            "matched_sets": "not_applicable",
            "seeds": "not_reported",
            "regimes": "not_reported",
            "player_rows": "not_reported",
            "event_rows": "not_reported",
            "utterance_rows": _count("results/bow_speech_stage_r2/bow_speech_utterance_dataset.csv"),
            "rollout_rows": "not_applicable",
            "candidate_rows": _count("results/bow_speech_stage_r2/bow_document_term_matrix.csv"),
            "independent_unit": "utterance and grouped game/template splits",
            "primary_outcome": "role-prediction ROC-AUC",
            "secondary_outcomes": "template OOD AUC and leakage checks",
            "formal_inference": "predictive validation",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "bow vocabulary and score manifests",
            "source_report": "results/bow_speech_stage_r2/bow_stage_r2_research_report.md",
            "source_data": "results/bow_speech_stage_r2/bow_role_prediction_metrics.csv",
            "evidence_status": "template_bound_predictive_success",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Utterances are not independent game outcomes.",
        },
        {
            "stage_id": "bow_stage_r3",
            "experiment_id": "guarded_bow_live_integration",
            "research_question": "RQ1;RQ4",
            "experiment_type": "matched live policy integration",
            "role_or_mechanism": "BoW-guided voting/belief updates",
            "policies_or_conditions": "7 live BoW conditions",
            "raw_game_rows": _count("results/bow_integration_stage_r3/r3_live_game_level_raw.csv"),
            "unique_games": _uniq("results/bow_integration_stage_r3/r3_live_game_level_raw.csv", "game_uid"),
            "matched_sets": _uniq("results/bow_integration_stage_r3/r3_live_game_level_raw.csv", "matched_set_id"),
            "seeds": "not_reported",
            "regimes": _uniq("results/bow_integration_stage_r3/r3_live_game_level_raw.csv", "behavioral_regime"),
            "player_rows": "not_reported",
            "event_rows": _count("results/bow_integration_stage_r3/r3_live_belief_update_raw.csv"),
            "utterance_rows": _count("results/bow_integration_stage_r3/r3_live_speech_event_raw.csv"),
            "rollout_rows": _count("results/bow_integration_stage_r3/r3_vote_disagreement_rollout_raw.csv"),
            "candidate_rows": "not_applicable",
            "independent_unit": "matched complete game set",
            "primary_outcome": "village win rate",
            "secondary_outcomes": "belief updates, vote disagreements, rollout diagnostics",
            "formal_inference": "yes",
            "multiplicity_method": "Holm",
            "manifest_or_hash": "R3 BoW policy manifests",
            "source_report": "results/bow_integration_stage_r3/r3_research_report.md",
            "source_data": "results/bow_integration_stage_r3/r3_primary_game_contrasts.csv",
            "evidence_status": "statistically_supported_harm_or_no_improvement",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Predictive BoW value did not imply live policy value.",
        },
        {
            "stage_id": "ml_stage1",
            "experiment_id": "observation_safe_ml_pilot",
            "research_question": "RQ4",
            "experiment_type": "pilot prediction and action-value analysis",
            "role_or_mechanism": "ML candidate scoring",
            "policies_or_conditions": "identity prediction and rollout pilot",
            "raw_game_rows": "not_reported",
            "unique_games": "not_reported",
            "matched_sets": "not_applicable",
            "seeds": "not_reported",
            "regimes": "not_reported",
            "player_rows": "not_reported",
            "event_rows": "not_reported",
            "utterance_rows": "not_applicable",
            "rollout_rows": "not_reported",
            "candidate_rows": "7155",
            "independent_unit": "decision states or game families, not candidate rows",
            "primary_outcome": "ROC-AUC",
            "secondary_outcomes": "surrogate action value",
            "formal_inference": "pilot only",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "not_applicable",
            "source_report": "results/ml_optimization_stage1/ml_stage1_research_report.md",
            "source_data": "results/ml_optimization_stage1/ml_identity_prediction_dataset.csv",
            "evidence_status": "superseded",
            "included_in_final_analysis": "yes_as_superseded",
            "exclusion_reason": "not_applicable",
            "notes": "Pilot AUC was later reduced by grouped validation.",
        },
        {
            "stage_id": "ml_stage15",
            "experiment_id": "grouped_full_state_validation",
            "research_question": "RQ4;RQ6",
            "experiment_type": "grouped validation and full-state rollout",
            "role_or_mechanism": "ML generalization",
            "policies_or_conditions": "grouped identity and rollout validations",
            "raw_game_rows": "not_reported",
            "unique_games": _uniq("results/ml_optimization_stage15/ml_full_rollout_detail_rows.csv", "game_id"),
            "matched_sets": "not_applicable",
            "seeds": "6",
            "regimes": "7",
            "player_rows": "not_reported",
            "event_rows": "not_reported",
            "utterance_rows": "not_applicable",
            "rollout_rows": _count("results/ml_optimization_stage15/ml_full_rollout_detail_rows.csv"),
            "candidate_rows": _count("results/ml_optimization_stage15/ml_full_rollout_wolf_kill_dataset.csv"),
            "independent_unit": "source game family and grouped decision state",
            "primary_outcome": "final-test ROC-AUC and rollout value",
            "secondary_outcomes": "policy regret",
            "formal_inference": "grouped validation",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "not_applicable",
            "source_report": "results/ml_optimization_stage15/ml_stage15_research_report.md",
            "source_data": "results/ml_optimization_stage15/ml_identity_generalization_metrics.csv",
            "evidence_status": "weak_inconclusive",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Candidate rows and rollout branches are not live games.",
        },
        {
            "stage_id": "ml_stage2a",
            "experiment_id": "frozen_ml_wolf_kill_live",
            "research_question": "RQ4",
            "experiment_type": "matched live policy test",
            "role_or_mechanism": "ML wolf night kill",
            "policies_or_conditions": "existing, frozen ML, hybrid, epsilon",
            "raw_game_rows": _count("results/ml_optimization_stage2a/wolf_kill_live_game_level_raw.csv"),
            "unique_games": _uniq("results/ml_optimization_stage2a/wolf_kill_live_game_level_raw.csv", "game_id"),
            "matched_sets": _uniq("results/ml_optimization_stage2a/wolf_kill_live_game_level_raw.csv", "matched_set_id"),
            "seeds": "20",
            "regimes": _uniq("results/ml_optimization_stage2a/wolf_kill_live_game_level_raw.csv", "behavioral_regime_id"),
            "player_rows": "not_reported",
            "event_rows": _count("results/ml_optimization_stage2a/wolf_kill_live_decision_raw.csv"),
            "utterance_rows": "not_applicable",
            "rollout_rows": "not_applicable",
            "candidate_rows": _count("results/ml_optimization_stage2a/wolf_kill_policy_predictions_raw.csv"),
            "independent_unit": "matched live complete-game set",
            "primary_outcome": "wolf win rate",
            "secondary_outcomes": "special-role kill rate and distribution shift",
            "formal_inference": "yes",
            "multiplicity_method": "Holm",
            "manifest_or_hash": "Stage 2A frozen model manifest",
            "source_report": "results/ml_optimization_stage2a/ml_stage2a_research_report.md",
            "source_data": "results/ml_optimization_stage2a/wolf_kill_primary_contrasts.csv",
            "evidence_status": "live_policy_harm_or_no_improvement",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Live policy outcomes outrank shadow policy value.",
        },
        {
            "stage_id": "ml_stage2b",
            "experiment_id": "offline_to_live_failure_diagnostics",
            "research_question": "RQ4",
            "experiment_type": "matched live diagnostic variants",
            "role_or_mechanism": "ML wolf night kill intervention frequency",
            "policies_or_conditions": "single, two-step, continuous, selective, shadow",
            "raw_game_rows": _count("results/ml_optimization_stage2b/stage2b_live_game_level_raw.csv"),
            "unique_games": _uniq("results/ml_optimization_stage2b/stage2b_live_game_level_raw.csv", "game_id"),
            "matched_sets": _uniq("results/ml_optimization_stage2b/stage2b_live_game_level_raw.csv", "matched_set_id"),
            "seeds": "not_reported",
            "regimes": _uniq("results/ml_optimization_stage2b/stage2b_live_game_level_raw.csv", "behavioral_regime_id"),
            "player_rows": "not_reported",
            "event_rows": _count("results/ml_optimization_stage2b/stage2b_live_decision_raw.csv"),
            "utterance_rows": "not_applicable",
            "rollout_rows": _count("results/ml_optimization_stage2b/stage2b_single_intervention_rollout_raw.csv"),
            "candidate_rows": _count("results/ml_optimization_stage2b/stage2b_policy_prediction_raw.csv"),
            "independent_unit": "matched live complete-game set",
            "primary_outcome": "wolf win rate",
            "secondary_outcomes": "intervention count and special-role targeting",
            "formal_inference": "yes",
            "multiplicity_method": "Holm",
            "manifest_or_hash": "Stage 2A frozen model reused",
            "source_report": "results/ml_optimization_stage2b/ml_stage2b_research_report.md",
            "source_data": "results/ml_optimization_stage2b/stage2b_primary_contrasts.csv",
            "evidence_status": "diagnostic_only",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "ML remains diagnostic only.",
        },
        {
            "stage_id": "r4_payoff_matrix",
            "experiment_id": "unified_payoff_ledger",
            "research_question": "RQ3",
            "experiment_type": "analysis-only payoff ledger",
            "role_or_mechanism": "role payoff decomposition",
            "policies_or_conditions": "core and extended payoff specifications",
            "raw_game_rows": _count("results/payoff_matrix_stage_r4/r4_game_level_payoff_raw.csv"),
            "unique_games": _uniq("results/payoff_matrix_stage_r4/r4_game_level_payoff_raw.csv", "game_id"),
            "matched_sets": _uniq("results/payoff_matrix_stage_r4/r4_game_level_payoff_raw.csv", "matched_set_id"),
            "seeds": "10",
            "regimes": "5",
            "player_rows": _count("results/payoff_matrix_stage_r4/r4_player_level_payoff_raw.csv"),
            "event_rows": "200660",
            "utterance_rows": "not_applicable",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "complete game; player rows clustered within game",
            "primary_outcome": "role payoff",
            "secondary_outcomes": "action and opportunity-cost decomposition",
            "formal_inference": "ledger validation",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "eee8007693ec6a484632f61444a53f6f8b1b9feb64b18c865f0edf704a15c7cd",
            "source_report": "results/payoff_matrix_stage_r4/r4_research_report.md",
            "source_data": "results/payoff_matrix_stage_r4/r4_player_level_payoff_raw.csv",
            "evidence_status": "unified_payoff_system_validated",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "R4 and R5 game rows overlap; do not sum as independent games.",
        },
        {
            "stage_id": "r5_financial_risk",
            "experiment_id": "financial_risk_metrics",
            "research_question": "RQ3",
            "experiment_type": "analysis-only risk metrics",
            "role_or_mechanism": "payoff volatility and downside risk",
            "policies_or_conditions": "core and extended specifications",
            "raw_game_rows": _count("results/financial_risk_stage_r5/r5_game_payoff_metrics_raw.csv"),
            "unique_games": _uniq("results/financial_risk_stage_r5/r5_game_payoff_metrics_raw.csv", "game_id"),
            "matched_sets": _uniq("results/financial_risk_stage_r5/r5_game_payoff_metrics_raw.csv", "matched_set_id"),
            "seeds": "10",
            "regimes": "5",
            "player_rows": _count("results/financial_risk_stage_r5/r5_player_payoff_metrics_raw.csv"),
            "event_rows": "200660",
            "utterance_rows": "not_applicable",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "complete game for bootstrap; player rows clustered within game",
            "primary_outcome": "risk-adjusted role payoff",
            "secondary_outcomes": "VaR-like, CVaR-like, Sharpe-like, Sortino-like metrics",
            "formal_inference": "bootstrap CIs and robustness",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "4b48f5aae165d6c30d5a13cd2e9c3e01f5b595ddbfeb93f7c1832b018f6861bf",
            "source_report": "results/financial_risk_stage_r5/r5_research_report.md",
            "source_data": "results/financial_risk_stage_r5/r5_role_expected_payoff_summary.csv",
            "evidence_status": "financial_analogy_supported",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Derived from R4 payoff data; do not double count R4 rows.",
        },
        {
            "stage_id": "r51_attribution",
            "experiment_id": "actor_specific_strategy_audit",
            "research_question": "RQ2;RQ3",
            "experiment_type": "actor-specific attribution correction",
            "role_or_mechanism": "strategy ownership",
            "policies_or_conditions": "actor-owned strategy rows",
            "raw_game_rows": "not_reported",
            "unique_games": "not_reported",
            "matched_sets": "not_reported",
            "seeds": "not_reported",
            "regimes": "not_reported",
            "player_rows": _count("results/financial_risk_stage_r51/r51_actor_specific_strategy_payoff_raw.csv"),
            "event_rows": "not_reported",
            "utterance_rows": "not_applicable",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "actor-specific strategy row clustered by source game",
            "primary_outcome": "actor payoff difference",
            "secondary_outcomes": "externality and premium attribution",
            "formal_inference": "yes where coverage exists",
            "multiplicity_method": "Holm where applicable",
            "manifest_or_hash": "R4/R5 frozen hashes",
            "source_report": "results/financial_risk_stage_r51/r51_research_report.md",
            "source_data": "results/financial_risk_stage_r51/r51_actor_specific_primary_contrasts.csv",
            "evidence_status": "attribution_corrected",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Supersedes global R5 labels for role-specific strategy claims.",
        },
        {
            "stage_id": "r6_role_strategy_synthesis",
            "experiment_id": "role_strategy_evidence_matrix",
            "research_question": "RQ2",
            "experiment_type": "synthesis",
            "role_or_mechanism": "all roles",
            "policies_or_conditions": "role strategy decision matrix",
            "raw_game_rows": "not_applicable",
            "unique_games": "not_applicable",
            "matched_sets": "not_applicable",
            "seeds": "not_applicable",
            "regimes": "not_applicable",
            "player_rows": "not_applicable",
            "event_rows": "not_applicable",
            "utterance_rows": "not_applicable",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "evidence row",
            "primary_outcome": "recommended tested policy",
            "secondary_outcomes": "evidence grade and contradictions",
            "formal_inference": "synthesis only",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "not_applicable",
            "source_report": "results/role_strategy_synthesis_stage_r6/r6_research_report.md",
            "source_data": "results/role_strategy_synthesis_stage_r6/r6_role_strategy_decision_matrix.csv",
            "evidence_status": "ready_for_targeted_gaps",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Refined by R6.1 targeted experiments and R6.2 metric audit.",
        },
        {
            "stage_id": "r61_targeted_strategy",
            "experiment_id": "targeted_role_strategy_gap_closure",
            "research_question": "RQ2;RQ3;RQ5",
            "experiment_type": "matched role-policy experiments",
            "role_or_mechanism": "Seer, Witch, Hunter, Werewolf, Villager",
            "policies_or_conditions": "30 targeted role policies",
            "raw_game_rows": "30000",
            "unique_games": "30000",
            "matched_sets": "5000 role-module matched sets",
            "seeds": "20",
            "regimes": "10",
            "player_rows": "not_reported",
            "event_rows": str(
                row_count("results/targeted_strategy_stage_r61/r61_hunter_action_raw.csv")
                + row_count("results/targeted_strategy_stage_r61/r61_seer_reveal_event_raw.csv")
                + row_count("results/targeted_strategy_stage_r61/r61_witch_action_raw.csv")
                + row_count("results/targeted_strategy_stage_r61/r61_wolf_action_and_deception_raw.csv")
                + row_count("results/targeted_strategy_stage_r61/r61_villager_vote_raw.csv")
            ),
            "utterance_rows": "not_applicable",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "matched role-module configuration set",
            "primary_outcome": "actor payoff and faction win rate",
            "secondary_outcomes": "risk metrics and action quality",
            "formal_inference": "yes",
            "multiplicity_method": "Holm within role modules",
            "manifest_or_hash": "R4/R5 frozen hashes",
            "source_report": "results/targeted_strategy_stage_r61/r61_research_report.md",
            "source_data": "results/targeted_strategy_stage_r61/r61_global_primary_contrasts.csv",
            "evidence_status": "primary_role_strategy_evidence",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Main source for final role-specific recommendations.",
        },
        {
            "stage_id": "r62_metrics_integrity",
            "experiment_id": "seer_survival_witch_potion_audit",
            "research_question": "RQ2;RQ3;RQ5",
            "experiment_type": "metric integrity audit",
            "role_or_mechanism": "Seer survival and Witch potion lifecycle",
            "policies_or_conditions": "seer reveal policies and witch joint policies",
            "raw_game_rows": "supplementary_metric_audit",
            "unique_games": "1200 seer + 1200 witch supplementary life-cycle games",
            "matched_sets": "not_reported",
            "seeds": "not_reported",
            "regimes": "not_reported",
            "player_rows": "not_reported",
            "event_rows": _count("results/metrics_integrity_stage_r62/r62_seer_life_history_raw.csv"),
            "utterance_rows": "not_applicable",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "reconstructable role life-cycle game",
            "primary_outcome": "metric validity and lifecycle waste",
            "secondary_outcomes": "post-reveal hazard, potion waste categories",
            "formal_inference": "audit and bootstrap summaries",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "0d5e284c625dd63181c6ee852e565a10506271cba3b3684da3b612c634d2e537",
            "source_report": "results/metrics_integrity_stage_r62/r62_research_report.md",
            "source_data": "results/metrics_integrity_stage_r62/r62_seer_survival_summary.csv; results/metrics_integrity_stage_r62/r62_witch_potion_waste_summary.csv",
            "evidence_status": "metric_integrity_corrected",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "Supersedes narrow terminal survival and earlier Witch waste proxy interpretations.",
        },
        {
            "stage_id": "r7_literature",
            "experiment_id": "systematic_literature_synthesis",
            "research_question": "RQ1;RQ2;RQ3;RQ4;RQ5;RQ6",
            "experiment_type": "literature synthesis",
            "role_or_mechanism": "all mechanisms",
            "policies_or_conditions": "64 retained sources",
            "raw_game_rows": "not_applicable",
            "unique_games": "not_applicable",
            "matched_sets": "not_applicable",
            "seeds": "not_applicable",
            "regimes": "not_applicable",
            "player_rows": "not_applicable",
            "event_rows": "not_applicable",
            "utterance_rows": "not_applicable",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "literature source and project finding mapping",
            "primary_outcome": "source coverage",
            "secondary_outcomes": "contradiction and financial analogy crosswalk",
            "formal_inference": "not_applicable",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "not_applicable",
            "source_report": "results/literature_synthesis_stage_r7/r7_research_report.md",
            "source_data": "results/literature_synthesis_stage_r7/r7_finding_literature_comparison_matrix.csv",
            "evidence_status": "ready_for_synthesis",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "R7.1 controls final bibliography eligibility.",
        },
        {
            "stage_id": "r71_doi_recency",
            "experiment_id": "doi_verified_recency_audit",
            "research_question": "RQ1;RQ2;RQ3;RQ4;RQ5;RQ6",
            "experiment_type": "DOI and recency bibliography audit",
            "role_or_mechanism": "literature integration",
            "policies_or_conditions": "44 final DOI-backed sources",
            "raw_game_rows": "not_applicable",
            "unique_games": "not_applicable",
            "matched_sets": "not_applicable",
            "seeds": "not_applicable",
            "regimes": "not_applicable",
            "player_rows": "not_applicable",
            "event_rows": "not_applicable",
            "utterance_rows": "not_applicable",
            "rollout_rows": "not_applicable",
            "candidate_rows": "not_applicable",
            "independent_unit": "literature source and finding-literature mapping",
            "primary_outcome": "DOI-only final bibliography",
            "secondary_outcomes": "recency share and foundational exception coverage",
            "formal_inference": "not_applicable",
            "multiplicity_method": "not_applicable",
            "manifest_or_hash": "not_applicable",
            "source_report": "results/literature_doi_recency_audit_stage_r71/r71_research_report.md",
            "source_data": "results/literature_doi_recency_audit_stage_r71/r71_revised_finding_literature_matrix.csv",
            "evidence_status": "doi_only_ready_for_r8",
            "included_in_final_analysis": "yes",
            "exclusion_reason": "not_applicable",
            "notes": "No no-DOI source may be used in final written-report citations.",
        },
    ]


def build_project_scale_summary() -> list[dict[str, str]]:
    inventory = build_experiment_inventory()
    r61_event_rows = int([row for row in inventory if row["stage_id"] == "r61_targeted_strategy"][0]["event_rows"])
    return [
        {
            "scale_metric": "total_complete_live_game_executions_from_game_level_rows",
            "minimum_confirmed_unique": "151450",
            "maximum_possible_rows": "170450",
            "can_be_summed_across_stages": "no",
            "source_basis": "game-level raw files plus summary-only multi-seed files where exact games per condition are reported",
            "overlap_caveat": "R4 and R5 share source games; seat-order rows include deterministic duplicates; summary-only ten-player stages may overlap configuration families.",
            "final_reporting_rule": "Report stage-specific counts and sample units, not one grand independent N.",
        },
        {
            "scale_metric": "matched_configuration_sets",
            "minimum_confirmed_unique": "19350",
            "maximum_possible_rows": "not_applicable",
            "can_be_summed_across_stages": "no",
            "source_basis": "matched_set_id counts in R3, R4/R5, ML live stages, seat-order-neutral, and R6.1 modules",
            "overlap_caveat": "Matched sets are defined within stage and cannot be pooled without stage clustering.",
            "final_reporting_rule": "Use stage-level matched-set counts for formal contrasts.",
        },
        {
            "scale_metric": "player_game_rows",
            "minimum_confirmed_unique": "80000",
            "maximum_possible_rows": "80000",
            "can_be_summed_across_stages": "no",
            "source_basis": "R4 and R5 player payoff files each have 40000 rows over the same payoff validation source games.",
            "overlap_caveat": "R4 and R5 are derived from the same player-game units.",
            "final_reporting_rule": "Use R5 for final risk table; use R4 for ledger validation.",
        },
        {
            "scale_metric": "event_rows",
            "minimum_confirmed_unique": str(200660 + r61_event_rows),
            "maximum_possible_rows": str(200660 + r61_event_rows + row_count("results/bow_integration_stage_r3/r3_live_belief_update_raw.csv")),
            "can_be_summed_across_stages": "no",
            "source_basis": "R4 payoff event rows and R6.1 role-action/vote event logs; R3 belief updates counted separately.",
            "overlap_caveat": "Event rows are nested within games and cannot be treated as independent outcomes.",
            "final_reporting_rule": "Use only for mechanism diagnostics.",
        },
        {
            "scale_metric": "utterance_rows",
            "minimum_confirmed_unique": _count("results/bow_speech_stage_r2/bow_speech_utterance_dataset.csv"),
            "maximum_possible_rows": str(row_count("results/bow_speech_stage_r2/bow_speech_utterance_dataset.csv") + row_count("results/bow_integration_stage_r3/r3_live_speech_event_raw.csv")),
            "can_be_summed_across_stages": "no",
            "source_basis": "R2 utterance dataset plus R3 live speech events.",
            "overlap_caveat": "Speech event rows are nested inside games and templates.",
            "final_reporting_rule": "Use for BoW feature and speech-signal analysis, not game outcome N.",
        },
        {
            "scale_metric": "vote_and_belief_update_rows",
            "minimum_confirmed_unique": str(row_count("results/bow_integration_stage_r3/r3_live_vote_decision_raw.csv") + row_count("results/bow_integration_stage_r3/r3_live_belief_update_raw.csv")),
            "maximum_possible_rows": str(row_count("results/bow_integration_stage_r3/r3_live_vote_decision_raw.csv") + row_count("results/bow_integration_stage_r3/r3_live_belief_update_raw.csv") + row_count("results/targeted_strategy_stage_r61/r61_villager_vote_raw.csv")),
            "can_be_summed_across_stages": "no",
            "source_basis": "R3 vote/belief rows and R6.1 villager vote rows.",
            "overlap_caveat": "Rows are nested in games and policies.",
            "final_reporting_rule": "Use for mechanism diagnostics only.",
        },
        {
            "scale_metric": "rollout_and_counterfactual_rows",
            "minimum_confirmed_unique": str(row_count("results/bow_integration_stage_r3/r3_vote_disagreement_rollout_raw.csv") + row_count("results/ml_optimization_stage15/ml_full_rollout_detail_rows.csv") + row_count("results/ml_optimization_stage2b/stage2b_single_intervention_rollout_raw.csv")),
            "maximum_possible_rows": str(row_count("results/bow_integration_stage_r3/r3_vote_disagreement_rollout_raw.csv") + row_count("results/ml_optimization_stage15/ml_full_rollout_detail_rows.csv") + row_count("results/ml_optimization_stage2b/stage2b_single_intervention_rollout_raw.csv")),
            "can_be_summed_across_stages": "no",
            "source_basis": "BoW and ML rollout/counterfactual diagnostic tables.",
            "overlap_caveat": "Rollout branches are simulated continuations, not live complete games.",
            "final_reporting_rule": "Report as diagnostic/counterfactual rows.",
        },
        {
            "scale_metric": "unique_seeds",
            "minimum_confirmed_unique": "at least 20",
            "maximum_possible_rows": "not_applicable",
            "can_be_summed_across_stages": "no",
            "source_basis": "R6.1 final seed registry plus earlier multi-seed stages.",
            "overlap_caveat": "Seed labels recur across stages and are not independent by themselves.",
            "final_reporting_rule": "Use seed robustness within stage.",
        },
        {
            "scale_metric": "behavioral_regimes",
            "minimum_confirmed_unique": "10",
            "maximum_possible_rows": "not_applicable",
            "can_be_summed_across_stages": "no",
            "source_basis": "R6.1 behavioral regime registry.",
            "overlap_caveat": "Regime definitions differ in early stages.",
            "final_reporting_rule": "Use regime robustness within comparable stages.",
        },
        {
            "scale_metric": "literature_sources_screened_or_retained",
            "minimum_confirmed_unique": "64",
            "maximum_possible_rows": "88 including R7.1 replacement-source identifiers",
            "can_be_summed_across_stages": "no",
            "source_basis": "R7 retained sources and R7.1 replacement registry.",
            "overlap_caveat": "Literature sources are not empirical simulation samples.",
            "final_reporting_rule": "Use DOI-only R7.1 final bibliography for final citations.",
        },
        {
            "scale_metric": "doi_eligible_final_literature_sources",
            "minimum_confirmed_unique": "44",
            "maximum_possible_rows": "44",
            "can_be_summed_across_stages": "yes_as_bibliography_count_only",
            "source_basis": "R7.1 final references and bibliography.",
            "overlap_caveat": "Bibliography entries support claims; they are not experimental outcomes.",
            "final_reporting_rule": "Every final literature citation must be from R7.1 final bibliography.",
        },
    ]
